CREATE TABLE `blueprint_step_progress` (
	`id` int AUTO_INCREMENT NOT NULL,
	`blueprintId` int NOT NULL,
	`stepId` varchar(100) NOT NULL,
	`status` enum('not_started','in_progress','review','completed','blocked') DEFAULT 'not_started',
	`progressPercent` int DEFAULT 0,
	`assignedSMEs` json,
	`outputs` json,
	`qaStatus` enum('pending','in_review','approved','rejected') DEFAULT 'pending',
	`qaFeedback` text,
	`qaApprovedBy` varchar(100),
	`qaApprovedAt` timestamp,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`notes` text,
	`blockerReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blueprint_step_progress_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `capital_raises` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`projectId` int,
	`name` varchar(200) NOT NULL,
	`roundType` enum('pre_seed','seed','series_a','series_b','series_c','growth','bridge','debt','grant','convertible') NOT NULL,
	`targetAmount` int NOT NULL,
	`currency` varchar(3) DEFAULT 'GBP',
	`minTicket` int,
	`maxTicket` int,
	`preMoneyValuation` int,
	`equityOffered` int,
	`targetCloseDate` timestamp,
	`actualCloseDate` timestamp,
	`status` enum('planning','preparing','active','closing','closed','cancelled') DEFAULT 'planning',
	`amountRaised` int DEFAULT 0,
	`investorCount` int DEFAULT 0,
	`pitchDeckUrl` varchar(500),
	`dataRoomUrl` varchar(500),
	`termSheetUrl` varchar(500),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `capital_raises_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `investor_commitments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`investorId` int NOT NULL,
	`capitalRaiseId` int NOT NULL,
	`commitmentType` enum('interest','soft_commit','hard_commit','signed','funded') NOT NULL,
	`amount` int NOT NULL,
	`currency` varchar(3) DEFAULT 'GBP',
	`terms` text,
	`specialConditions` text,
	`status` enum('pending','confirmed','cancelled','completed') DEFAULT 'pending',
	`commitmentDate` timestamp,
	`fundingDate` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `investor_commitments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `investor_interactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`investorId` int NOT NULL,
	`capitalRaiseId` int,
	`interactionType` enum('intro_email','intro_call','pitch_meeting','follow_up','due_diligence','term_sheet','negotiation','closing','rejection') NOT NULL,
	`interactionDate` timestamp NOT NULL,
	`subject` varchar(300),
	`notes` text,
	`outcome` enum('positive','neutral','negative','pending') DEFAULT 'pending',
	`nextAction` varchar(300),
	`nextActionDate` timestamp,
	`attachments` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `investor_interactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `investors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(200) NOT NULL,
	`type` enum('angel','hnwi','family_office','vc','pe','bank','government','strategic') NOT NULL,
	`organization` varchar(200),
	`ticketSizeMin` int,
	`ticketSizeMax` int,
	`currency` varchar(3) DEFAULT 'GBP',
	`sectors` json,
	`stages` json,
	`geographies` json,
	`dealTypes` json,
	`email` varchar(200),
	`phone` varchar(50),
	`linkedin` varchar(300),
	`website` varchar(300),
	`relationshipStatus` enum('cold','warm','hot','active','invested','passed') DEFAULT 'cold',
	`introducedBy` varchar(200),
	`lastContactDate` timestamp,
	`notes` text,
	`tags` json,
	`source` varchar(100),
	`isVerified` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `investors_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `project_blueprints` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`projectId` int,
	`blueprintType` varchar(50) NOT NULL,
	`name` varchar(200) NOT NULL,
	`description` text,
	`intakeResponses` json,
	`intakeCompletedAt` timestamp,
	`currentStepId` varchar(100),
	`completedSteps` json,
	`passedGates` json,
	`pendingGates` json,
	`deliverables` json,
	`assignedSMEs` json,
	`status` enum('intake','in_progress','review','completed','on_hold','cancelled') DEFAULT 'intake',
	`startedAt` timestamp,
	`targetCompletionDate` timestamp,
	`completedAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `project_blueprints_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `registered_devices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`deviceId` varchar(100) NOT NULL,
	`deviceName` varchar(200) NOT NULL,
	`deviceType` enum('desktop','mobile','tablet') NOT NULL,
	`browser` varchar(100),
	`os` varchar(100),
	`webauthnCredentialId` text,
	`webauthnPublicKey` text,
	`status` enum('active','suspended','revoked') DEFAULT 'active',
	`isTrusted` boolean DEFAULT false,
	`trustExpiresAt` timestamp,
	`lastUsedAt` timestamp,
	`lastIpAddress` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `registered_devices_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `security_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`passwordEnabled` boolean DEFAULT true,
	`biometricEnabled` boolean DEFAULT false,
	`hardwareKeyEnabled` boolean DEFAULT false,
	`totpEnabled` boolean DEFAULT false,
	`totpSecret` text,
	`sessionTimeout` int DEFAULT 30,
	`vaultTimeout` int DEFAULT 5,
	`requireReauthForVault` boolean DEFAULT true,
	`allowRememberDevice` boolean DEFAULT true,
	`maxTrustedDevices` int DEFAULT 5,
	`alertOnNewDevice` boolean DEFAULT true,
	`alertOnFailedAttempts` boolean DEFAULT true,
	`failedAttemptThreshold` int DEFAULT 3,
	`emergencyLockEnabled` boolean DEFAULT false,
	`emergencyLockCode` varchar(100),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `security_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `security_settings_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `triple_ai_validation` (
	`id` int AUTO_INCREMENT NOT NULL,
	`blueprintId` int NOT NULL,
	`stepId` varchar(100),
	`gateId` varchar(100),
	`deliverableId` varchar(100),
	`validationType` enum('step_output','qa_gate','deliverable','final_review') NOT NULL,
	`validator1` varchar(100) NOT NULL,
	`validator1Result` enum('pass','fail','conditional'),
	`validator1Feedback` text,
	`validator1Score` int,
	`validator2` varchar(100) NOT NULL,
	`validator2Result` enum('pass','fail','conditional'),
	`validator2Feedback` text,
	`validator2Score` int,
	`validator3` varchar(100) NOT NULL,
	`validator3Result` enum('pass','fail','conditional'),
	`validator3Feedback` text,
	`validator3Score` int,
	`overallResult` enum('pass','fail','conditional'),
	`consensusScore` int,
	`consolidatedFeedback` text,
	`userOverride` boolean DEFAULT false,
	`userOverrideReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `triple_ai_validation_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `vault_credentials` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(200) NOT NULL,
	`category` enum('api_key','oauth_token','password','certificate','ssh_key','other') NOT NULL,
	`encryptedData` text NOT NULL,
	`encryptionVersion` int DEFAULT 1,
	`service` varchar(100),
	`username` varchar(200),
	`url` varchar(500),
	`expiresAt` timestamp,
	`rotationReminder` boolean DEFAULT false,
	`lastRotated` timestamp,
	`accessLevel` enum('personal','shared','system') DEFAULT 'personal',
	`lastAccessedAt` timestamp,
	`accessCount` int DEFAULT 0,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vault_credentials_id` PRIMARY KEY(`id`)
);
