CREATE TABLE `investor_invites` (
	`id` int AUTO_INCREMENT NOT NULL,
	`landingPageId` int NOT NULL,
	`investorId` int,
	`email` varchar(255) NOT NULL,
	`name` varchar(255),
	`personalMessage` text,
	`inviteToken` varchar(100) NOT NULL,
	`status` varchar(50) DEFAULT 'sent',
	`sentAt` timestamp NOT NULL DEFAULT (now()),
	`openedAt` timestamp,
	`firstViewedAt` timestamp,
	`lastViewedAt` timestamp,
	`totalViews` int DEFAULT 0,
	`totalWatchTime` int DEFAULT 0,
	`expiresAt` timestamp,
	CONSTRAINT `investor_invites_id` PRIMARY KEY(`id`),
	CONSTRAINT `investor_invites_inviteToken_unique` UNIQUE(`inviteToken`)
);
--> statement-breakpoint
CREATE TABLE `landing_page_access_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`landingPageId` int NOT NULL,
	`visitorEmail` varchar(255),
	`visitorName` varchar(255),
	`investorId` int,
	`sessionId` varchar(100) NOT NULL,
	`ipAddress` varchar(50),
	`userAgent` text,
	`referrer` varchar(500),
	`deviceType` varchar(50),
	`browser` varchar(100),
	`os` varchar(100),
	`country` varchar(100),
	`city` varchar(100),
	`videosWatched` json,
	`totalWatchTime` int DEFAULT 0,
	`documentsDownloaded` json,
	`socialClicks` json,
	`accessedAt` timestamp NOT NULL DEFAULT (now()),
	`lastActivityAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `landing_page_access_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pitch_landing_pages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`packId` int NOT NULL,
	`slug` varchar(100) NOT NULL,
	`accessType` varchar(50) DEFAULT 'link',
	`password` varchar(255),
	`expiresAt` timestamp,
	`maxViews` int,
	`customTitle` varchar(255),
	`customMessage` text,
	`showDownloads` boolean DEFAULT true,
	`showSocials` boolean DEFAULT true,
	`showContact` boolean DEFAULT true,
	`pitchDeckUrl` varchar(500),
	`onePagerUrl` varchar(500),
	`financialsUrl` varchar(500),
	`additionalDocs` json,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pitch_landing_pages_id` PRIMARY KEY(`id`),
	CONSTRAINT `pitch_landing_pages_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `pitch_videos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`packId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`type` varchar(50) NOT NULL,
	`description` text,
	`duration` int,
	`videoUrl` varchar(500),
	`thumbnailUrl` varchar(500),
	`videoProvider` varchar(50),
	`videoId` varchar(100),
	`scriptId` int,
	`displayOrder` int DEFAULT 0,
	`isPublished` boolean DEFAULT false,
	`views` int DEFAULT 0,
	`completionRate` decimal(5,2) DEFAULT '0',
	`avgWatchTime` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pitch_videos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `video_pitch_packs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`projectId` int,
	`name` varchar(255) NOT NULL,
	`companyName` varchar(255) NOT NULL,
	`tagline` varchar(500),
	`description` text,
	`logoUrl` varchar(500),
	`primaryColor` varchar(20) DEFAULT '#8B5CF6',
	`secondaryColor` varchar(20) DEFAULT '#EC4899',
	`websiteUrl` varchar(500),
	`linkedinUrl` varchar(500),
	`twitterUrl` varchar(500),
	`instagramUrl` varchar(500),
	`youtubeUrl` varchar(500),
	`contactName` varchar(255),
	`contactEmail` varchar(255),
	`contactPhone` varchar(50),
	`status` varchar(50) DEFAULT 'draft',
	`totalViews` int DEFAULT 0,
	`uniqueViews` int DEFAULT 0,
	`totalWatchTime` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `video_pitch_packs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `video_scripts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`packId` int NOT NULL,
	`videoType` varchar(50) NOT NULL,
	`title` varchar(255) NOT NULL,
	`targetDuration` int DEFAULT 120,
	`hook` text,
	`introduction` text,
	`mainContent` text,
	`keyPoints` json,
	`callToAction` text,
	`fullScript` text,
	`visualSuggestions` json,
	`graphicsSuggestions` json,
	`tone` varchar(50) DEFAULT 'professional',
	`speakingPace` varchar(50) DEFAULT 'moderate',
	`sourceData` json,
	`version` int DEFAULT 1,
	`status` varchar(50) DEFAULT 'draft',
	`feedback` text,
	`revisionNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `video_scripts_id` PRIMARY KEY(`id`)
);
