CREATE TABLE `funding_assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`assessmentId` varchar(100) NOT NULL,
	`userId` int NOT NULL,
	`ideaId` int NOT NULL,
	`programId` varchar(100) NOT NULL,
	`eligibilityScore` float,
	`eligibilityStatus` enum('highly_eligible','eligible','partially_eligible','not_eligible','needs_review') NOT NULL DEFAULT 'needs_review',
	`criteriaResults` json,
	`strengths` json,
	`gaps` json,
	`recommendations` json,
	`estimatedFunding` float,
	`applicationReadiness` float,
	`generatedDocuments` json,
	`notes` text,
	`assessedAt` timestamp NOT NULL DEFAULT (now()),
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `funding_assessments_id` PRIMARY KEY(`id`),
	CONSTRAINT `funding_assessments_assessmentId_unique` UNIQUE(`assessmentId`)
);
--> statement-breakpoint
CREATE TABLE `funding_programs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`programId` varchar(100) NOT NULL,
	`name` varchar(300) NOT NULL,
	`country` enum('UAE','UK','EU','US','Other') NOT NULL,
	`region` varchar(100),
	`type` enum('grant','loan','tax_credit','equity','accelerator','incubator','competition','other') NOT NULL,
	`provider` varchar(200) NOT NULL,
	`description` text,
	`fundingMin` float,
	`fundingMax` float,
	`equityRequired` float,
	`interestRate` float,
	`repaymentTerms` text,
	`eligibilityCriteria` json,
	`requiredDocuments` json,
	`applicationProcess` json,
	`deadlines` json,
	`sectors` json,
	`stages` json,
	`websiteUrl` text,
	`applicationUrl` text,
	`contactEmail` varchar(320),
	`successRate` float,
	`averageProcessingDays` int,
	`isActive` boolean NOT NULL DEFAULT true,
	`lastUpdated` timestamp,
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `funding_programs_id` PRIMARY KEY(`id`),
	CONSTRAINT `funding_programs_programId_unique` UNIQUE(`programId`)
);
