CREATE TABLE `customer_accounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`ventureName` varchar(200) NOT NULL,
	`customerName` varchar(200) NOT NULL,
	`customerType` enum('individual','business','enterprise') NOT NULL DEFAULT 'individual',
	`email` varchar(320),
	`phone` varchar(50),
	`company` varchar(200),
	`industry` varchar(100),
	`country` varchar(100),
	`city` varchar(100),
	`status` enum('prospect','active','churned','paused') NOT NULL DEFAULT 'prospect',
	`lifetimeValue` float DEFAULT 0,
	`currency` varchar(10) NOT NULL DEFAULT 'AED',
	`acquisitionSource` varchar(200),
	`acquisitionDate` timestamp,
	`churnDate` timestamp,
	`churnReason` text,
	`stripeCustomerId` varchar(200),
	`notes` text,
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customer_accounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pipeline_opportunities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`ventureName` varchar(200) NOT NULL,
	`opportunityName` varchar(300) NOT NULL,
	`customerName` varchar(200),
	`customerContact` varchar(320),
	`stage` enum('lead','qualified','proposal','negotiation','verbal_yes','contract_sent','won','lost') NOT NULL DEFAULT 'lead',
	`probability` int DEFAULT 10,
	`estimatedValue` float NOT NULL,
	`currency` varchar(10) NOT NULL DEFAULT 'AED',
	`expectedCloseDate` timestamp,
	`actualCloseDate` timestamp,
	`lostReason` text,
	`nextAction` text,
	`nextActionDate` timestamp,
	`assignedTo` varchar(200),
	`source` varchar(200),
	`notes` text,
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pipeline_opportunities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pricing_tiers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`streamId` int NOT NULL,
	`tierName` varchar(100) NOT NULL,
	`price` float NOT NULL,
	`currency` varchar(10) NOT NULL DEFAULT 'AED',
	`billingPeriod` enum('one_time','monthly','quarterly','annual') NOT NULL,
	`features` json,
	`limitations` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`displayOrder` int DEFAULT 0,
	`stripePriceId` varchar(200),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pricing_tiers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `revenue_forecasts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`ventureName` varchar(200),
	`streamId` int,
	`forecastPeriod` varchar(20) NOT NULL,
	`periodType` enum('monthly','quarterly','annual') NOT NULL,
	`projectedRevenue` float NOT NULL,
	`actualRevenue` float,
	`currency` varchar(10) NOT NULL DEFAULT 'AED',
	`assumptions` text,
	`confidence` enum('low','medium','high') DEFAULT 'medium',
	`variance` float,
	`variancePercentage` float,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `revenue_forecasts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `revenue_metrics_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`snapshotDate` timestamp NOT NULL,
	`totalMRR` float DEFAULT 0,
	`totalARR` float DEFAULT 0,
	`totalRevenueMTD` float DEFAULT 0,
	`totalRevenueYTD` float DEFAULT 0,
	`pipelineValue` float DEFAULT 0,
	`weightedPipelineValue` float DEFAULT 0,
	`activeCustomers` int DEFAULT 0,
	`newCustomersMTD` int DEFAULT 0,
	`churnedCustomersMTD` int DEFAULT 0,
	`averageRevenuePerCustomer` float DEFAULT 0,
	`currency` varchar(10) NOT NULL DEFAULT 'AED',
	`ventureBreakdown` json,
	`streamBreakdown` json,
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `revenue_metrics_snapshots_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `revenue_streams` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`ventureName` varchar(200) NOT NULL,
	`streamName` varchar(200) NOT NULL,
	`streamType` enum('subscription','one_time','recurring','licensing','consulting','commission','advertising','affiliate','other') NOT NULL,
	`status` enum('active','paused','planned','discontinued') NOT NULL DEFAULT 'planned',
	`currency` varchar(10) NOT NULL DEFAULT 'AED',
	`monthlyRecurring` float DEFAULT 0,
	`annualRecurring` float DEFAULT 0,
	`averageTransactionValue` float DEFAULT 0,
	`transactionsPerMonth` int DEFAULT 0,
	`marginPercentage` float DEFAULT 0,
	`paymentProcessor` varchar(100),
	`processorConnected` boolean DEFAULT false,
	`pricingModel` text,
	`targetCustomerSegment` varchar(200),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `revenue_streams_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `revenue_transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`streamId` int NOT NULL,
	`transactionDate` timestamp NOT NULL,
	`amount` float NOT NULL,
	`currency` varchar(10) NOT NULL DEFAULT 'AED',
	`status` enum('pending','completed','failed','refunded') NOT NULL DEFAULT 'pending',
	`customerName` varchar(200),
	`customerEmail` varchar(320),
	`description` text,
	`invoiceNumber` varchar(100),
	`paymentMethod` varchar(100),
	`processorTransactionId` varchar(200),
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `revenue_transactions_id` PRIMARY KEY(`id`)
);
