CREATE TABLE `customer_feedback_aggregations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`surveyId` int NOT NULL,
	`userId` int NOT NULL,
	`totalResponses` int DEFAULT 0,
	`averageSentimentScore` float,
	`wtpDistribution` json,
	`averageSuggestedPrice` float,
	`priceRangeMin` float,
	`priceRangeMax` float,
	`sentimentBySegment` json,
	`wtpBySegment` json,
	`topPositives` json,
	`topConcerns` json,
	`topSuggestions` json,
	`goNoGoRecommendation` enum('strong_go','go','conditional','no_go','strong_no_go'),
	`recommendedPricePoint` float,
	`keyRecommendations` json,
	`aggregatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `customer_feedback_aggregations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customer_personas` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`age` int NOT NULL,
	`gender` enum('male','female','non_binary','prefer_not_to_say') NOT NULL,
	`nationality` varchar(100) NOT NULL,
	`ethnicity` varchar(100),
	`location` varchar(200) NOT NULL,
	`occupation` varchar(200) NOT NULL,
	`industry` varchar(100) NOT NULL,
	`jobLevel` enum('entry','mid','senior','executive','founder','retired','student') NOT NULL,
	`companySize` enum('solo','startup','small','medium','large','enterprise'),
	`annualIncome` enum('under_25k','25k_50k','50k_75k','75k_100k','100k_150k','150k_250k','250k_500k','500k_1m','over_1m'),
	`personalityType` varchar(50),
	`buyingStyle` enum('impulsive','researcher','bargain_hunter','brand_loyal','quality_focused','value_seeker'),
	`techSavviness` enum('low','medium','high','expert'),
	`riskTolerance` enum('conservative','moderate','aggressive'),
	`interests` json,
	`painPoints` json,
	`goals` json,
	`bio` text NOT NULL,
	`avatar` varchar(500),
	`segment` varchar(100),
	`tier` enum('core','extended','niche') NOT NULL DEFAULT 'core',
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customer_personas_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customer_survey_responses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`surveyId` int NOT NULL,
	`personaId` int NOT NULL,
	`responses` json NOT NULL,
	`overallSentiment` enum('very_negative','negative','neutral','positive','very_positive'),
	`willingnessToPay` enum('definitely_not','unlikely','maybe','likely','definitely'),
	`suggestedPricePoint` float,
	`currency` varchar(10) DEFAULT 'AED',
	`keyInsights` json,
	`concerns` json,
	`suggestions` json,
	`generatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `customer_survey_responses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customer_surveys` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(200) NOT NULL,
	`description` text,
	`surveyType` enum('idea_validation','pricing_feedback','feature_priority','product_feedback','market_research','competitor_comparison','user_experience') NOT NULL,
	`innovationIdeaId` int,
	`ventureName` varchar(200),
	`productName` varchar(200),
	`questions` json NOT NULL,
	`targetSegments` json,
	`sampleSize` int DEFAULT 25,
	`status` enum('draft','active','completed','archived') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completedAt` timestamp,
	CONSTRAINT `customer_surveys_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `focus_group_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(200) NOT NULL,
	`objective` text NOT NULL,
	`sessionType` enum('concept_testing','pricing_research','feature_prioritization','competitive_analysis','brand_perception','user_journey_mapping') NOT NULL,
	`innovationIdeaId` int,
	`ventureName` varchar(200),
	`participantPersonaIds` json NOT NULL,
	`participantCount` int DEFAULT 0,
	`discussionGuide` json,
	`transcript` text,
	`keyThemes` json,
	`consensusPoints` json,
	`divergencePoints` json,
	`status` enum('planned','in_progress','completed','analyzed') NOT NULL DEFAULT 'planned',
	`scheduledFor` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `focus_group_sessions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `innovation_validation_checkpoints` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`innovationIdeaId` int NOT NULL,
	`flywheelStage` enum('capture','assess','validate','develop','commercialize') NOT NULL,
	`validationType` enum('customer_survey','focus_group','pricing_test','concept_test','prototype_feedback') NOT NULL,
	`surveyId` int,
	`focusGroupId` int,
	`validationScore` float,
	`passedValidation` boolean,
	`decision` enum('proceed','pivot','iterate','abandon','pending') NOT NULL DEFAULT 'pending',
	`decisionRationale` text,
	`smeReviewCompleted` boolean DEFAULT false,
	`smeReviewNotes` text,
	`chiefOfStaffApproved` boolean DEFAULT false,
	`chiefOfStaffNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `innovation_validation_checkpoints_id` PRIMARY KEY(`id`)
);
