CREATE TABLE `assessment_outliers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`assessmentId` int NOT NULL,
	`assessmentPeriod` varchar(20) NOT NULL,
	`categoryId` int NOT NULL,
	`categoryNumber` int NOT NULL,
	`categoryName` varchar(200) NOT NULL,
	`expertId` varchar(100) NOT NULL,
	`expertName` varchar(200) NOT NULL,
	`expertPanel` varchar(100) NOT NULL,
	`expertScore` int NOT NULL,
	`panelAverage` float NOT NULL,
	`overallAverage` float NOT NULL,
	`deviation` float NOT NULL,
	`deviationPercentage` float NOT NULL,
	`outlierType` enum('high','low') NOT NULL,
	`severity` enum('minor','moderate','significant','extreme') NOT NULL,
	`reviewStatus` enum('pending','under_review','resolved','accepted') NOT NULL DEFAULT 'pending',
	`chiefOfStaffReviewed` boolean DEFAULT false,
	`chiefOfStaffNotes` text,
	`reviewedAt` timestamp,
	`conversationRequested` boolean DEFAULT false,
	`conversationCompleted` boolean DEFAULT false,
	`conversationNotes` text,
	`conversationOutcome` text,
	`resolution` enum('score_adjusted','score_validated','insight_captured','system_improvement_identified','dismissed'),
	`resolutionNotes` text,
	`flaggedAt` timestamp NOT NULL DEFAULT (now()),
	`resolvedAt` timestamp,
	CONSTRAINT `assessment_outliers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `expert_conversation_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`outlierId` int,
	`assessmentId` int,
	`expertId` varchar(100) NOT NULL,
	`expertName` varchar(200) NOT NULL,
	`expertPanel` varchar(100) NOT NULL,
	`categoryNumber` int,
	`categoryName` varchar(200),
	`conversationType` enum('outlier_investigation','score_clarification','deep_dive','recommendation_discussion','general_feedback') NOT NULL,
	`messages` json NOT NULL,
	`keyInsights` json,
	`actionItems` json,
	`scoreAdjustment` int,
	`status` enum('in_progress','completed','follow_up_needed') NOT NULL DEFAULT 'in_progress',
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `expert_conversation_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `external_research_references` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(500) NOT NULL,
	`authors` json,
	`publicationDate` timestamp,
	`sourceType` enum('academic_paper','industry_report','news_article','blog_post','government_data','market_research','competitor_website','social_media','podcast','video','book','other') NOT NULL,
	`url` varchar(1000),
	`publisher` varchar(300),
	`abstract` text,
	`keyFindings` json,
	`relevantQuotes` json,
	`topics` json,
	`ventures` json,
	`credibilityScore` float DEFAULT 0.5,
	`relevanceScore` float DEFAULT 0.5,
	`linkedInsightIds` json,
	`status` enum('active','archived','outdated') NOT NULL DEFAULT 'active',
	`importedAt` timestamp NOT NULL DEFAULT (now()),
	`lastReviewedAt` timestamp,
	CONSTRAINT `external_research_references_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `insight_usage_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`insightId` int NOT NULL,
	`usageType` enum('decision_support','survey_design','validation_reference','report_citation','strategy_input','presentation','conversation_reference','search_result') NOT NULL,
	`usageContext` varchar(300),
	`relatedEntityType` varchar(100),
	`relatedEntityId` int,
	`usedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `insight_usage_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `insights_repository` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(300) NOT NULL,
	`summary` text NOT NULL,
	`fullContent` text,
	`sourceType` enum('customer_survey','focus_group','sme_assessment','expert_conversation','external_research','market_data','competitor_analysis','user_observation','manual_entry') NOT NULL,
	`sourceId` int,
	`sourceReference` varchar(500),
	`sourceName` varchar(300),
	`category` enum('customer_need','pricing_insight','feature_request','market_trend','competitive_intelligence','user_behavior','pain_point','opportunity','risk','validation_result','technical_feedback','ux_feedback','business_model','regulatory','other') NOT NULL,
	`tags` json,
	`ventures` json,
	`products` json,
	`relevanceScore` float DEFAULT 0.5,
	`confidenceLevel` enum('low','medium','high','verified') DEFAULT 'medium',
	`validatedBy` varchar(200),
	`validatedAt` timestamp,
	`timesReferenced` int DEFAULT 0,
	`lastReferencedAt` timestamp,
	`relatedInsightIds` json,
	`supersededBy` int,
	`status` enum('active','archived','superseded','disputed') NOT NULL DEFAULT 'active',
	`capturedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `insights_repository_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `knowledge_topics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(200) NOT NULL,
	`parentTopicId` int,
	`path` varchar(500),
	`description` text,
	`insightCount` int DEFAULT 0,
	`lastInsightAt` timestamp,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `knowledge_topics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `kpi_categories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`categoryNumber` int NOT NULL,
	`name` varchar(200) NOT NULL,
	`description` text NOT NULL,
	`scoringCriteria` json,
	`excellentThreshold` int DEFAULT 90,
	`goodThreshold` int DEFAULT 75,
	`adequateThreshold` int DEFAULT 60,
	`developingThreshold` int DEFAULT 40,
	`assessingPanels` json,
	`weight` float DEFAULT 1,
	`priority` enum('critical','high','medium','maintain') DEFAULT 'medium',
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `kpi_categories_id` PRIMARY KEY(`id`),
	CONSTRAINT `kpi_categories_categoryNumber_unique` UNIQUE(`categoryNumber`)
);
--> statement-breakpoint
CREATE TABLE `kpi_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`snapshotPeriod` varchar(20) NOT NULL,
	`snapshotDate` timestamp NOT NULL,
	`overallScore` float NOT NULL,
	`previousScore` float,
	`scoreChange` float,
	`categoryScores` json NOT NULL,
	`excellentCount` int DEFAULT 0,
	`goodCount` int DEFAULT 0,
	`adequateCount` int DEFAULT 0,
	`developingCount` int DEFAULT 0,
	`criticalCount` int DEFAULT 0,
	`highestCategory` varchar(200),
	`highestScore` int,
	`lowestCategory` varchar(200),
	`lowestScore` int,
	`targetScore` float,
	`gapToTarget` float,
	`totalExpertsAssessed` int DEFAULT 0,
	`panelsParticipated` json,
	`outliersIdentified` int DEFAULT 0,
	`outliersResolved` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `kpi_snapshots_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `panel_assessment_aggregations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`assessmentPeriod` varchar(20) NOT NULL,
	`panelName` varchar(100) NOT NULL,
	`categoryId` int NOT NULL,
	`categoryNumber` int NOT NULL,
	`categoryName` varchar(200) NOT NULL,
	`averageScore` float NOT NULL,
	`medianScore` float,
	`minScore` int,
	`maxScore` int,
	`standardDeviation` float,
	`individualScores` json,
	`expertCount` int DEFAULT 0,
	`consensusLevel` enum('strong','moderate','weak','divided'),
	`aggregatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `panel_assessment_aggregations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `prior_research_checks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`triggerType` enum('new_survey','new_focus_group','new_assessment','new_idea_validation','manual_search') NOT NULL,
	`triggerId` int,
	`searchQuery` text,
	`searchCategories` json,
	`searchVentures` json,
	`searchTags` json,
	`insightsFound` int DEFAULT 0,
	`relevantInsightIds` json,
	`externalRefsFound` int DEFAULT 0,
	`relevantExternalIds` json,
	`summaryGenerated` text,
	`gapsIdentified` json,
	`actionTaken` enum('proceeded_with_new_research','used_existing_insights','modified_research_scope','cancelled_duplicate'),
	`actionRationale` text,
	`checkedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `prior_research_checks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sme_individual_assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`assessmentPeriod` varchar(20) NOT NULL,
	`assessmentDate` timestamp NOT NULL,
	`expertId` varchar(100) NOT NULL,
	`expertName` varchar(200) NOT NULL,
	`expertPanel` varchar(100) NOT NULL,
	`expertSpecialization` varchar(200),
	`categoryId` int NOT NULL,
	`categoryNumber` int NOT NULL,
	`categoryName` varchar(200) NOT NULL,
	`score` int NOT NULL,
	`scoreOutOf10` float,
	`rationale` text NOT NULL,
	`strengths` json,
	`weaknesses` json,
	`evidence` json,
	`recommendations` json,
	`confidenceLevel` enum('low','medium','high') DEFAULT 'medium',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sme_individual_assessments_id` PRIMARY KEY(`id`)
);
