import { boolean, int, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

// ─── Projects ────────────────────────────────────────────────────────────────
export const projects = mysqlTable("projects", {
  id: int("id").autoincrement().primaryKey(),
  slug: varchar("slug", { length: 64 }).notNull().unique(),
  name: varchar("name", { length: 128 }).notNull(),
  description: text("description"),
  status: mysqlEnum("status", ["red", "amber", "green"]).default("green").notNull(),
  accentColor: varchar("accentColor", { length: 16 }).default("#00D4FF").notNull(),
  initials: varchar("initials", { length: 4 }).notNull(),
  overview: text("overview"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type Project = typeof projects.$inferSelect;

// ─── Project Genesis Assessments ─────────────────────────────────────────────
export const genesisAssessments = mysqlTable("genesis_assessments", {
  id: int("id").autoincrement().primaryKey(),
  ideaTitle: varchar("ideaTitle", { length: 256 }).notNull(),
  ideaSummary: text("ideaSummary").notNull(),
  stage: mysqlEnum("stage", ["concept", "market", "model", "team", "risk", "execution", "complete"]).default("concept").notNull(),
  answers: text("answers").default("{}").notNull(),
  aiAnalysis: text("aiAnalysis").default("{}").notNull(),
  overallScore: int("overallScore"),
  recommendation: mysqlEnum("recommendation", ["proceed", "pivot", "pause", "stop"]),
  convertedToProjectId: int("convertedToProjectId"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type GenesisAssessment = typeof genesisAssessments.$inferSelect;

// ─── Innovation Hub ───────────────────────────────────────────────────────────
export const innovations = mysqlTable("innovations", {
  id: int("id").autoincrement().primaryKey(),
  title: varchar("title", { length: 256 }).notNull(),
  description: text("description"),
  category: mysqlEnum("category", ["product", "process", "market", "technology", "partnership", "other"]).default("other").notNull(),
  status: mysqlEnum("status", ["idea", "exploring", "testing", "adopted", "archived"]).default("idea").notNull(),
  linkedProjectId: int("linkedProjectId"),
  aiInsight: text("aiInsight"),
  tags: text("tags").default("[]").notNull(),
  // Extra columns added directly in SQL for InnovationPage
  projectName: varchar("projectName", { length: 128 }),
  stage: varchar("stage", { length: 64 }).default("Concept"),
  votes: int("votes").default(0),
  // Flywheel automation fields
  sourceUrl: text("sourceUrl"),
  sourceName: varchar("sourceName", { length: 256 }),
  autoGenerated: boolean("autoGenerated").default(false).notNull(),
  dailyCycleId: int("dailyCycleId"),
  flywheelStage: mysqlEnum("flywheelStage", ["captured", "assessed", "shortlisted", "promoted", "held", "archived"]).default("captured").notNull(),
  assessmentScore: int("assessmentScore"),
  assessmentData: text("assessmentData").default("{}").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type Innovation = typeof innovations.$inferSelect;

// ─── Idea Sources ─────────────────────────────────────────────────────────────
export const ideaSources = mysqlTable("idea_sources", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 128 }).notNull(),
  type: mysqlEnum("type", ["rss", "web", "medium", "telegram", "manual"]).default("web").notNull(),
  url: text("url"),
  sector: varchar("sector", { length: 128 }).default("general").notNull(),
  active: boolean("active").default(true).notNull(),
  lastFetchedAt: timestamp("lastFetchedAt"),
  fetchCount: int("fetchCount").default(0).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type IdeaSource = typeof ideaSources.$inferSelect;

// ─── Daily Idea Cycles ────────────────────────────────────────────────────────
export const ideaDailyCycles = mysqlTable("idea_daily_cycles", {
  id: int("id").autoincrement().primaryKey(),
  cycleDate: varchar("cycleDate", { length: 16 }).notNull(),
  candidateIds: text("candidateIds").default("[]").notNull(),
  selectedId: int("selectedId"),
  promotedAt: timestamp("promotedAt"),
  status: mysqlEnum("status", ["generating", "ready", "selected", "promoted", "skipped"]).default("generating").notNull(),
  agentNotes: text("agentNotes").default(""),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type IdeaDailyCycle = typeof ideaDailyCycles.$inferSelect;

// ─── Agent Reflections ────────────────────────────────────────────────────────
export const agentReflections = mysqlTable("agent_reflections", {
  id: int("id").autoincrement().primaryKey(),
  agentId: int("agentId"),
  weekStart: varchar("weekStart", { length: 16 }).notNull(),
  runsAnalysed: int("runsAnalysed").default(0).notNull(),
  thingsWorked: text("thingsWorked").default(""),
  thingsMissed: text("thingsMissed").default(""),
  proposedPatch: text("proposedPatch").notNull(),
  status: mysqlEnum("status", ["pending", "accepted", "rejected"]).default("pending").notNull(),
  reviewedAt: timestamp("reviewedAt"),
  appliedAt: timestamp("appliedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type AgentReflection = typeof agentReflections.$inferSelect;

// ─── AI SMEs ─────────────────────────────────────────────────────────────────
export const aiSmes = mysqlTable("ai_smes", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 128 }).notNull(),
  title: varchar("title", { length: 256 }).notNull(),
  domain: varchar("domain", { length: 64 }).notNull(),
  subDomain: varchar("subDomain", { length: 128 }),
  expertise: text("expertise").default("[]").notNull(),
  systemPrompt: text("systemPrompt").notNull(),
  isActive: int("isActive").default(1).notNull(),
  consultCount: int("consultCount").default(0).notNull(),
  avgRating: int("avgRating"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type AiSme = typeof aiSmes.$inferSelect;

// ─── Consultations ────────────────────────────────────────────────────────────
export const consultations = mysqlTable("consultations", {
  id: int("id").autoincrement().primaryKey(),
  smeId: int("smeId").notNull(),
  smeName: varchar("smeName", { length: 128 }).notNull(),
  projectId: int("projectId"),
  messages: text("messages").default("[]").notNull(),
  rating: int("rating"),
  feedback: text("feedback"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type Consultation = typeof consultations.$inferSelect;

// ─── Documents ───────────────────────────────────────────────────────────────
export const documents = mysqlTable("documents", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId"),
  name: varchar("name", { length: 256 }).notNull(),
  fileType: varchar("fileType", { length: 16 }).notNull(),
  fileSize: int("fileSize"),
  storageKey: varchar("storageKey", { length: 512 }).notNull(),
  storageUrl: text("storageUrl"),
  isConfidential: int("isConfidential").default(0).notNull(),
  uploadedBy: varchar("uploadedBy", { length: 64 }),
  tags: text("tags").default("[]").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type Document = typeof documents.$inferSelect;

// ─── The Vault — Constant Learning ───────────────────────────────────────────
export const learningEntries = mysqlTable("learning_entries", {
  id: int("id").autoincrement().primaryKey(),
  source: mysqlEnum("source", ["victoria", "sme", "genesis", "project", "user"]).notNull(),
  sourceId: varchar("sourceId", { length: 64 }),
  category: varchar("category", { length: 64 }).notNull(),
  insight: text("insight").notNull(),
  context: text("context").default("{}").notNull(),
  confidence: int("confidence").default(50).notNull(),
  appliedCount: int("appliedCount").default(0).notNull(),
  isVerified: int("isVerified").default(0).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type LearningEntry = typeof learningEntries.$inferSelect;

// ─── Victoria Conversations ───────────────────────────────────────────────────
export const victoriaConversations = mysqlTable("victoria_conversations", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId"),
  context: varchar("context", { length: 64 }).default("general").notNull(),
  messages: text("messages").default("[]").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type VictoriaConversation = typeof victoriaConversations.$inferSelect;

// ─── Tasks ───────────────────────────────────────────────────────────────────
export const tasks = mysqlTable("tasks", {
  id: int("id").autoincrement().primaryKey(),
  title: varchar("title", { length: 256 }).notNull(),
  description: text("description").default(""),
  projectId: int("projectId"),
  assignee: varchar("assignee", { length: 128 }).default(""),
  dueDate: timestamp("dueDate"),
  priority: mysqlEnum("priority", ["low", "medium", "high", "critical"]).default("medium").notNull(),
  status: mysqlEnum("status", ["todo", "in_progress", "done", "blocked"]).default("todo").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type Task = typeof tasks.$inferSelect;

// ─── Decisions ────────────────────────────────────────────────────────────────
export const decisions = mysqlTable("decisions", {
  id: int("id").autoincrement().primaryKey(),
  title: varchar("title", { length: 256 }).notNull(),
  context: text("context").default(""),
  rationale: text("rationale").default(""),
  outcome: text("outcome").default(""),
  projectId: int("projectId"),
  impact: mysqlEnum("impact", ["low", "medium", "high", "critical"]).default("medium").notNull(),
  status: mysqlEnum("status", ["active", "superseded", "reversed"]).default("active").notNull(),
  madeBy: varchar("madeBy", { length: 128 }).default("Jonathan"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type Decision = typeof decisions.$inferSelect;

// ─── Calendar Events ──────────────────────────────────────────────────────────
export const calendarEvents = mysqlTable("calendar_events", {
  id: int("id").autoincrement().primaryKey(),
  title: varchar("title", { length: 256 }).notNull(),
  startTime: timestamp("startTime").notNull(),
  endTime: timestamp("endTime").notNull(),
  projectSlug: varchar("projectSlug", { length: 64 }).default(""),
  location: varchar("location", { length: 256 }).default(""),
  notes: text("notes").default(""),
  isAllDay: int("isAllDay").default(0).notNull(),
  source: varchar("source", { length: 32 }).default("manual").notNull(),
  externalId: varchar("externalId", { length: 256 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type CalendarEvent = typeof calendarEvents.$inferSelect;

// ─── Financial Data ───────────────────────────────────────────────────────────
export const financialData = mysqlTable("financial_data", {
  id: int("id").autoincrement().primaryKey(),
  companySlug: varchar("companySlug", { length: 64 }).notNull().unique(),
  companyName: varchar("companyName", { length: 128 }).notNull(),
  cashGbp: int("cashGbp").default(0).notNull(),
  burnMonthlyGbp: int("burnMonthlyGbp").default(0).notNull(),
  revenueMonthlyGbp: int("revenueMonthlyGbp").default(0).notNull(),
  notes: text("notes").default(""),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type FinancialData = typeof financialData.$inferSelect;

// ─── Settings ─────────────────────────────────────────────────────────────────
export const settings = mysqlTable("settings", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().unique(),
  victoriaStyle: mysqlEnum("victoriaStyle", ["direct", "detailed", "brief"]).default("direct").notNull(),
  victoriaAutobrief: int("victoriaAutobrief").default(1).notNull(),
  notificationsEmail: int("notificationsEmail").default(1).notNull(),
  notificationsPush: int("notificationsPush").default(1).notNull(),
  googleCalendarConnected: int("googleCalendarConnected").default(0).notNull(),
  outlookConnected: int("outlookConnected").default(0).notNull(),
  gmailConnected: int("gmailConnected").default(0).notNull(),
  timezone: varchar("timezone", { length: 64 }).default("Europe/London").notNull(),
  currency: varchar("currency", { length: 8 }).default("GBP").notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type Settings = typeof settings.$inferSelect;

// ─── Project Milestones ───────────────────────────────────────────────────────
export const milestones = mysqlTable("milestones", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId").notNull(),
  title: varchar("title", { length: 256 }).notNull(),
  description: text("description").default(""),
  dueDate: timestamp("dueDate"),
  status: mysqlEnum("status", ["pending", "in_progress", "complete", "overdue"]).default("pending").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type Milestone = typeof milestones.$inferSelect;

// ─── Generated Reports ────────────────────────────────────────────────────────
export const generatedReports = mysqlTable("generated_reports", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId"),
  reportType: mysqlEnum("reportType", ["status", "board_pack", "weekly_brief", "financial", "custom"]).default("status").notNull(),
  title: varchar("title", { length: 256 }).notNull(),
  content: text("content").notNull(),
  storageKey: varchar("storageKey", { length: 512 }),
  storageUrl: text("storageUrl"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type GeneratedReport = typeof generatedReports.$inferSelect;

// ─── Signal Actions (Morning Signal live data) ────────────────────────────────
export const signalActions = mysqlTable("signal_actions", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId"),
  projectName: varchar("projectName", { length: 128 }).notNull(),
  type: mysqlEnum("type", ["task", "decision", "email", "escalation", "review"]).default("task").notNull(),
  title: varchar("title", { length: 256 }).notNull(),
  description: text("description").default(""),
  priority: mysqlEnum("priority", ["low", "medium", "high", "critical"]).default("medium").notNull(),
  dueTime: varchar("dueTime", { length: 32 }).default(""),
  status: mysqlEnum("status", ["pending", "approved", "delegated", "escalated", "dismissed"]).default("pending").notNull(),
  linkedTaskId: int("linkedTaskId"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type SignalAction = typeof signalActions.$inferSelect;

// ─── AI Agents ────────────────────────────────────────────────────────────────
export const agents = mysqlTable("agents", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 128 }).notNull(),
  role: varchar("role", { length: 128 }).notNull(),
  description: text("description").default(""),
  capabilities: varchar("capabilities", { length: 2048 }).default("[]").notNull(),
  status: mysqlEnum("status", ["active", "paused", "archived"]).default("active").notNull(),
  projectId: int("projectId"),
  accentColor: varchar("accentColor", { length: 16 }).default("#6366f1").notNull(),
  lastRunAt: timestamp("lastRunAt"),
  runCount: int("runCount").default(0).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type Agent = typeof agents.$inferSelect;

export const agentRuns = mysqlTable("agent_runs", {
  id: int("id").autoincrement().primaryKey(),
  agentId: int("agentId").notNull(),
  projectId: int("projectId"),
  taskId: int("taskId"),
  status: mysqlEnum("status", ["queued", "running", "completed", "failed"]).default("queued").notNull(),
  prompt: text("prompt").default(""),
  result: text("result").default(""),
  errorMessage: text("errorMessage").default(""),
  startedAt: timestamp("startedAt"),
  completedAt: timestamp("completedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type AgentRun = typeof agentRuns.$inferSelect;
