import React, { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import {
  Plus, Lightbulb, Zap, ArrowUpRight, Loader2, ThumbsUp,
  Bot, RefreshCw, CheckCircle2, Clock, XCircle, ChevronRight,
  Rocket, Brain, Link
} from "lucide-react";

const FLYWHEEL_STYLES: Record<string, string> = {
  captured:    "bg-slate-50 text-slate-600 border-slate-200",
  assessed:    "bg-blue-50 text-blue-600 border-blue-200",
  shortlisted: "bg-amber-50 text-amber-600 border-amber-200",
  promoted:    "bg-emerald-50 text-emerald-600 border-emerald-200",
  held:        "bg-orange-50 text-orange-600 border-orange-200",
  archived:    "bg-slate-50 text-slate-400 border-slate-200",
};

const FLYWHEEL_STAGES = ["captured", "assessed", "shortlisted", "promoted", "held", "archived"] as const;
type FlywheelStage = typeof FLYWHEEL_STAGES[number];

type IdeaRow = {
  id: number;
  title: string;
  description: string | null;
  status: string;
  flywheelStage: string;
  autoGenerated: boolean;
  assessmentScore: number | null;
  tags: string;
  linkedProjectId: number | null;
  votes: number;
  createdAt: Date;
};

export default function InnovationPage() {
  const [tab, setTab] = useState("flywheel");
  const [addOpen, setAddOpen] = useState(false);
  const [form, setForm] = useState({ title: "", description: "", url: "" });
  const [genesisIdeaId, setGenesisIdeaId] = useState<number | null>(null);

  const { data: ideas = [], refetch } = trpc.innovation.list.useQuery();
  const { data: reflectionStats } = trpc.agentReflection.stats.useQuery();
  const { data: reflections = [] } = trpc.agentReflection.list.useQuery({ status: "pending" });

  const createIdea = trpc.innovation.create.useMutation({
    onSuccess: () => {
      toast.success("Idea captured — assessment running");
      setAddOpen(false);
      setForm({ title: "", description: "", url: "" });
      refetch();
    },
    onError: () => toast.error("Failed to capture idea"),
  });

  const captureUrl = trpc.innovation.captureFromUrl.useMutation({
    onSuccess: () => {
      toast.success("URL analysed and captured");
      setAddOpen(false);
      setForm({ title: "", description: "", url: "" });
      refetch();
    },
    onError: () => toast.error("Failed to analyse URL"),
  });

  const voteIdea = trpc.innovation.vote.useMutation({ onSuccess: () => refetch() });

  const promoteToGenesis = trpc.innovation.promoteToFlywheel.useMutation({
    onSuccess: () => {
      toast.success("Promoted to Project Genesis");
      setGenesisIdeaId(null);
      refetch();
    },
    onError: () => toast.error("Promotion failed"),
  });

  const reviewReflection = trpc.agentReflection.review.useMutation({
    onSuccess: (_, vars) => {
      toast.success(vars.decision === "accepted" ? "Patch accepted and applied" : "Patch rejected");
      refetch();
    },
  });

  const typedIdeas = ideas as IdeaRow[];
  const flywheelIdeas = typedIdeas.filter(i => i.flywheelStage !== "archived");
  const autoIdeas = typedIdeas.filter(i => i.autoGenerated);
  const shortlisted = typedIdeas.filter(i => i.flywheelStage === "shortlisted");
  const promoted = typedIdeas.filter(i => i.flywheelStage === "promoted");

  return (
    <div className="p-4 sm:p-6 max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-xl font-bold text-foreground flex items-center gap-2">
            <Zap className="h-5 w-5 text-amber-500" />
            Innovation Hub
          </h1>
          <p className="text-sm text-muted-foreground mt-0.5">Autonomous flywheel — 5 ideas captured daily, 1 promoted</p>
        </div>
        <Button size="sm" className="gap-1.5" onClick={() => setAddOpen(true)}>
          <Plus className="h-3.5 w-3.5" /> Capture Idea
        </Button>
      </div>

      {/* Stats row */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-3 mb-6">
        {[
          { label: "Total Captured", value: typedIdeas.length, icon: Lightbulb, color: "text-slate-500" },
          { label: "Auto-Generated", value: autoIdeas.length, icon: Bot, color: "text-blue-500" },
          { label: "Shortlisted", value: shortlisted.length, icon: CheckCircle2, color: "text-amber-500" },
          { label: "To Genesis", value: promoted.length, icon: Rocket, color: "text-emerald-500" },
          { label: "Patches Pending", value: reflectionStats?.pending ?? 0, icon: Brain, color: "text-purple-500" },
        ].map((stat) => (
          <div key={stat.label} className="rounded-xl border border-border bg-card p-3">
            <stat.icon className={`h-4 w-4 ${stat.color} mb-2`} />
            <p className="text-2xl font-bold text-foreground">{stat.value}</p>
            <p className="text-xs text-muted-foreground mt-0.5">{stat.label}</p>
          </div>
        ))}
      </div>

      <Tabs value={tab} onValueChange={setTab}>
        <TabsList className="mb-5">
          <TabsTrigger value="flywheel">Flywheel</TabsTrigger>
          <TabsTrigger value="reflections">
            Agent Reflections
            {(reflectionStats?.pending ?? 0) > 0 && (
              <span className="ml-1.5 h-4 w-4 rounded-full bg-amber-500 text-white text-[10px] flex items-center justify-center">
                {reflectionStats?.pending}
              </span>
            )}
          </TabsTrigger>
        </TabsList>

        {/* ── Flywheel tab ── */}
        <TabsContent value="flywheel">
          {/* Stage columns */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
            {(["captured", "shortlisted", "promoted"] as FlywheelStage[]).map(stage => {
              const stageIdeas = typedIdeas.filter(i => i.flywheelStage === stage);
              return (
                <div key={stage} className="rounded-xl border border-border bg-card/50 p-4">
                  <div className="flex items-center justify-between mb-3">
                    <span className={`text-xs font-semibold uppercase tracking-wide px-2 py-0.5 rounded-full border ${FLYWHEEL_STYLES[stage]}`}>
                      {stage}
                    </span>
                    <span className="text-xs text-muted-foreground">{stageIdeas.length}</span>
                  </div>
                  <div className="space-y-2">
                    {stageIdeas.slice(0, 5).map(idea => (
                      <div key={idea.id} className="p-3 rounded-lg border border-border bg-background hover:border-primary/30 transition-colors group">
                        <div className="flex items-start justify-between gap-2">
                          <p className="text-xs font-medium text-foreground leading-snug">{idea.title}</p>
                          {idea.autoGenerated && (
                            <Bot className="h-3 w-3 text-blue-400 shrink-0 mt-0.5" />
                          )}
                        </div>
                        {idea.assessmentScore != null && (
                          <div className="mt-2 flex items-center gap-1.5">
                            <div className="flex-1 h-1 rounded-full bg-muted overflow-hidden">
                              <div
                                className="h-full rounded-full bg-primary transition-all"
                                style={{ width: `${idea.assessmentScore}%` }}
                              />
                            </div>
                            <span className="text-[10px] text-muted-foreground">{idea.assessmentScore}</span>
                          </div>
                        )}
                        {stage === "shortlisted" && (
                          <Button
                            size="sm"
                            variant="outline"
                            className="mt-2 w-full h-6 text-[10px] gap-1"
                            onClick={() => setGenesisIdeaId(idea.id)}
                          >
                            <Rocket className="h-3 w-3" /> Send to Genesis
                          </Button>
                        )}
                        {stage === "promoted" && (
                          <div className="mt-1.5 flex items-center gap-1 text-[10px] text-emerald-600">
                            <CheckCircle2 className="h-3 w-3" /> In Genesis
                          </div>
                        )}
                      </div>
                    ))}
                    {stageIdeas.length === 0 && (
                      <p className="text-xs text-muted-foreground text-center py-4">
                        {stage === "captured" ? "Next daily run at 06:00 UTC" : "None yet"}
                      </p>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          {/* All ideas list */}
          <div>
            <h3 className="text-sm font-semibold text-foreground mb-3">All Ideas</h3>
            {typedIdeas.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-12 text-center">
                <Lightbulb className="h-10 w-10 text-muted-foreground/30 mb-3" />
                <p className="text-sm text-muted-foreground">No ideas yet. The daily agent runs at 06:00 UTC.</p>
                <Button size="sm" className="mt-4 gap-1.5" onClick={() => setAddOpen(true)}>
                  <Plus className="h-3.5 w-3.5" /> Capture First Idea
                </Button>
              </div>
            ) : (
              <div className="space-y-2">
                {typedIdeas.map((idea) => (
                  <div key={idea.id} className="flex items-center gap-3 p-3 rounded-xl border border-border bg-card hover:border-primary/30 transition-colors">
                    <div className="h-7 w-7 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                      {idea.autoGenerated ? <Bot className="h-3.5 w-3.5 text-blue-500" /> : <Lightbulb className="h-3.5 w-3.5 text-primary" />}
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-foreground truncate">{idea.title}</p>
                      <div className="flex items-center gap-2 mt-0.5 flex-wrap">
                        <span className={`text-[10px] px-1.5 py-0 rounded-full border font-medium ${FLYWHEEL_STYLES[idea.flywheelStage] ?? ""}`}>
                          {idea.flywheelStage}
                        </span>
                        {idea.assessmentScore != null && (
                          <span className="text-[10px] text-muted-foreground">Score: {idea.assessmentScore}</span>
                        )}
                      </div>
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      {idea.flywheelStage === "shortlisted" && (
                        <Button size="sm" variant="outline" className="h-6 text-[10px] gap-1 px-2"
                          onClick={() => setGenesisIdeaId(idea.id)}>
                          <Rocket className="h-3 w-3" /> Genesis
                        </Button>
                      )}
                      <button
                        onClick={() => voteIdea.mutate({ id: idea.id })}
                        className="flex items-center gap-1 text-xs text-muted-foreground hover:text-primary transition-colors">
                        <ThumbsUp className="h-3.5 w-3.5" />
                        {idea.votes ?? 0}
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </TabsContent>

        {/* ── Agent Reflections tab ── */}
        <TabsContent value="reflections">
          <div className="space-y-4">
            {reflections.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-12 text-center">
                <Brain className="h-10 w-10 text-muted-foreground/30 mb-3" />
                <p className="text-sm text-muted-foreground">No pending reflections. The weekly distiller runs every Sunday at 03:00 UTC.</p>
              </div>
            ) : (
              reflections.map((r: { id: number; weekStart: string; runsAnalysed: number; thingsWorked: string | null; thingsMissed: string | null; proposedPatch: string | null; status: string }) => (
                <div key={r.id} className="rounded-xl border border-amber-200 bg-amber-50/30 p-5">
                  <div className="flex items-start justify-between gap-3 mb-4">
                    <div>
                      <p className="text-sm font-semibold text-foreground">Week of {r.weekStart}</p>
                      <p className="text-xs text-muted-foreground mt-0.5">{r.runsAnalysed} agent runs analysed</p>
                    </div>
                    <Badge variant="outline" className="bg-amber-50 text-amber-600 border-amber-200 text-[10px]">
                      <Clock className="h-3 w-3 mr-1" /> Pending Review
                    </Badge>
                  </div>

                  {r.thingsWorked && (
                    <div className="mb-3">
                      <p className="text-xs font-medium text-emerald-700 mb-1 flex items-center gap-1">
                        <CheckCircle2 className="h-3 w-3" /> What Worked
                      </p>
                      <p className="text-xs text-muted-foreground whitespace-pre-wrap">{r.thingsWorked}</p>
                    </div>
                  )}

                  {r.thingsMissed && (
                    <div className="mb-3">
                      <p className="text-xs font-medium text-red-700 mb-1 flex items-center gap-1">
                        <XCircle className="h-3 w-3" /> What Was Missed
                      </p>
                      <p className="text-xs text-muted-foreground whitespace-pre-wrap">{r.thingsMissed}</p>
                    </div>
                  )}

                  {r.proposedPatch && (
                    <div className="mb-4 p-3 rounded-lg bg-background border border-border">
                      <p className="text-xs font-medium text-foreground mb-1 flex items-center gap-1">
                        <Brain className="h-3 w-3 text-purple-500" /> Proposed Patch
                      </p>
                      <p className="text-xs text-muted-foreground whitespace-pre-wrap">{r.proposedPatch}</p>
                    </div>
                  )}

                  <div className="flex gap-2">
                    <Button
                      size="sm"
                      className="gap-1.5 bg-emerald-600 hover:bg-emerald-700"
                      disabled={reviewReflection.isPending}
                      onClick={() => reviewReflection.mutate({ id: r.id, decision: "accepted" })}
                    >
                      <CheckCircle2 className="h-3.5 w-3.5" /> Accept Patch
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      className="gap-1.5"
                      disabled={reviewReflection.isPending}
                      onClick={() => reviewReflection.mutate({ id: r.id, decision: "rejected" })}
                    >
                      <XCircle className="h-3.5 w-3.5" /> Reject
                    </Button>
                  </div>
                </div>
              ))
            )}
          </div>
        </TabsContent>
      </Tabs>

      {/* Capture Idea Dialog */}
      <Dialog open={addOpen} onOpenChange={setAddOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader><DialogTitle>Capture Idea</DialogTitle></DialogHeader>
          <div className="space-y-3">
            <p className="text-xs text-muted-foreground">Add a title and description, or paste a URL from Medium/news and the agent will analyse it.</p>
            <Input
              placeholder="URL (Medium article, news story, etc.)"
              value={form.url}
              onChange={e => setForm(f => ({ ...f, url: e.target.value }))}
            />
            <div className="relative">
              <div className="absolute inset-0 flex items-center"><span className="w-full border-t" /></div>
              <div className="relative flex justify-center text-xs uppercase"><span className="bg-background px-2 text-muted-foreground">or write it</span></div>
            </div>
            <Input
              placeholder="Idea title"
              value={form.title}
              onChange={e => setForm(f => ({ ...f, title: e.target.value }))}
            />
            <Textarea
              placeholder="Description or story"
              rows={3}
              value={form.description}
              onChange={e => setForm(f => ({ ...f, description: e.target.value }))}
            />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setAddOpen(false)}>Cancel</Button>
            {form.url ? (
              <Button
                disabled={captureUrl.isPending}
                onClick={() => captureUrl.mutate({ url: form.url })}
              >
                {captureUrl.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : "Analyse URL"}
              </Button>
            ) : (
              <Button
                disabled={!form.title.trim() || createIdea.isPending}
                onClick={() => createIdea.mutate({ title: form.title, description: form.description })}
              >
                {createIdea.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : "Capture"}
              </Button>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Genesis Promotion Confirmation */}
      <Dialog open={genesisIdeaId !== null} onOpenChange={() => setGenesisIdeaId(null)}>
        <DialogContent className="max-w-sm">
          <DialogHeader><DialogTitle className="flex items-center gap-2"><Rocket className="h-4 w-4 text-emerald-500" /> Send to Project Genesis</DialogTitle></DialogHeader>
          <p className="text-sm text-muted-foreground">This will create a Genesis assessment and run all 7 phases autonomously. The full process takes 2–5 minutes.</p>
          <DialogFooter>
            <Button variant="outline" onClick={() => setGenesisIdeaId(null)}>Cancel</Button>
            <Button
              className="bg-emerald-600 hover:bg-emerald-700"
              disabled={promoteToGenesis.isPending}
              onClick={() => genesisIdeaId && promoteToGenesis.mutate({ id: genesisIdeaId })}
            >
              {promoteToGenesis.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : "Launch Genesis"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
