/**
 * Customer Focus Group Personas
 * 
 * Initial set of 100 diverse customer personas covering various:
 * - Age ranges (18-75+)
 * - Nationalities and ethnicities
 * - Professional backgrounds
 * - Income levels
 * - Technology comfort levels
 * - Decision-making styles
 * 
 * These personas are used for:
 * - Product/service validation
 * - Price point testing
 * - Feature prioritization
 * - Go-to-market feedback
 */

export interface CustomerPersona {
  id: string;
  name: string;
  age: number;
  gender: 'male' | 'female' | 'non_binary';
  nationality: string;
  ethnicity: string;
  location: string;
  occupation: string;
  industry: string;
  incomeLevel: 'low' | 'medium' | 'high' | 'very_high';
  educationLevel: 'high_school' | 'bachelors' | 'masters' | 'doctorate' | 'professional';
  techComfort: 1 | 2 | 3 | 4 | 5; // 1=low, 5=high
  decisionStyle: 'analytical' | 'intuitive' | 'collaborative' | 'impulsive';
  riskTolerance: 'conservative' | 'moderate' | 'aggressive';
  buyingMotivation: 'price' | 'quality' | 'convenience' | 'status' | 'innovation';
  bio: string;
  painPoints: string[];
  goals: string[];
  preferredChannels: string[];
}

export const CUSTOMER_PERSONAS: CustomerPersona[] = [
  // Age Group: 18-25 (Young Professionals / Students)
  {
    id: 'cp_001',
    name: 'Aisha Rahman',
    age: 23,
    gender: 'female',
    nationality: 'Bangladeshi',
    ethnicity: 'South Asian',
    location: 'Dubai, UAE',
    occupation: 'Junior Marketing Analyst',
    industry: 'Marketing',
    incomeLevel: 'medium',
    educationLevel: 'bachelors',
    techComfort: 5,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'Recent graduate working at a digital marketing agency in Dubai. Active on social media and always looking for tools that can give her an edge in her career. Values efficiency and modern design.',
    painPoints: ['Limited budget', 'Time pressure', 'Proving value to senior colleagues'],
    goals: ['Career advancement', 'Building expertise', 'Work-life balance'],
    preferredChannels: ['Instagram', 'LinkedIn', 'YouTube']
  },
  {
    id: 'cp_002',
    name: 'Marcus Chen',
    age: 24,
    gender: 'male',
    nationality: 'American',
    ethnicity: 'Asian American',
    location: 'San Francisco, USA',
    occupation: 'Software Developer',
    industry: 'Technology',
    incomeLevel: 'high',
    educationLevel: 'bachelors',
    techComfort: 5,
    decisionStyle: 'analytical',
    riskTolerance: 'aggressive',
    buyingMotivation: 'innovation',
    bio: 'Early-career developer at a tech startup. Passionate about AI and automation. Willing to try new tools if they solve real problems. Values open-source and transparency.',
    painPoints: ['Information overload', 'Tool fatigue', 'Keeping up with tech trends'],
    goals: ['Technical mastery', 'Building side projects', 'Joining a unicorn'],
    preferredChannels: ['Twitter/X', 'Reddit', 'Hacker News']
  },
  {
    id: 'cp_003',
    name: 'Fatima Al-Sayed',
    age: 22,
    gender: 'female',
    nationality: 'Egyptian',
    ethnicity: 'Arab',
    location: 'Cairo, Egypt',
    occupation: 'Business Student',
    industry: 'Education',
    incomeLevel: 'low',
    educationLevel: 'bachelors',
    techComfort: 4,
    decisionStyle: 'collaborative',
    riskTolerance: 'conservative',
    buyingMotivation: 'price',
    bio: 'Final year business student aspiring to start her own e-commerce business. Budget-conscious but ambitious. Relies heavily on peer recommendations.',
    painPoints: ['Limited resources', 'Lack of experience', 'Family expectations'],
    goals: ['Graduate with honors', 'Launch business', 'Financial independence'],
    preferredChannels: ['WhatsApp', 'Facebook', 'TikTok']
  },
  {
    id: 'cp_004',
    name: 'James Okonkwo',
    age: 25,
    gender: 'male',
    nationality: 'Nigerian',
    ethnicity: 'African',
    location: 'Lagos, Nigeria',
    occupation: 'Fintech Product Manager',
    industry: 'Financial Services',
    incomeLevel: 'medium',
    educationLevel: 'bachelors',
    techComfort: 5,
    decisionStyle: 'analytical',
    riskTolerance: 'moderate',
    buyingMotivation: 'quality',
    bio: 'Rising star in Lagos fintech scene. Manages a mobile payments product. Data-driven decision maker who values reliability over flashy features.',
    painPoints: ['Infrastructure challenges', 'Regulatory complexity', 'Talent retention'],
    goals: ['Product success', 'Industry recognition', 'International expansion'],
    preferredChannels: ['LinkedIn', 'Twitter/X', 'Podcasts']
  },
  {
    id: 'cp_005',
    name: 'Sofia Martinez',
    age: 21,
    gender: 'female',
    nationality: 'Mexican',
    ethnicity: 'Hispanic',
    location: 'Mexico City, Mexico',
    occupation: 'Graphic Designer',
    industry: 'Creative',
    incomeLevel: 'low',
    educationLevel: 'bachelors',
    techComfort: 4,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'convenience',
    bio: 'Freelance designer building her portfolio. Values tools that are beautiful and intuitive. Price-sensitive but will pay for quality that saves time.',
    painPoints: ['Inconsistent income', 'Client management', 'Standing out in crowded market'],
    goals: ['Build client base', 'Create signature style', 'Remote work flexibility'],
    preferredChannels: ['Instagram', 'Behance', 'Pinterest']
  },

  // Age Group: 26-35 (Established Professionals)
  {
    id: 'cp_006',
    name: 'David Kim',
    age: 32,
    gender: 'male',
    nationality: 'South Korean',
    ethnicity: 'East Asian',
    location: 'Seoul, South Korea',
    occupation: 'Investment Banker',
    industry: 'Finance',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 4,
    decisionStyle: 'analytical',
    riskTolerance: 'aggressive',
    buyingMotivation: 'status',
    bio: 'Senior associate at a major investment bank. Works long hours and values any tool that can give him an edge. Willing to pay premium for premium results.',
    painPoints: ['Time scarcity', 'Information asymmetry', 'Work-life imbalance'],
    goals: ['Make VP', 'Build wealth', 'Eventually start own fund'],
    preferredChannels: ['Bloomberg', 'LinkedIn', 'Email']
  },
  {
    id: 'cp_007',
    name: 'Priya Sharma',
    age: 29,
    gender: 'female',
    nationality: 'Indian',
    ethnicity: 'South Asian',
    location: 'Bangalore, India',
    occupation: 'Engineering Manager',
    industry: 'Technology',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 5,
    decisionStyle: 'collaborative',
    riskTolerance: 'moderate',
    buyingMotivation: 'quality',
    bio: 'Leads a team of 15 engineers at a major tech company. Values tools that improve team productivity. Makes decisions collaboratively with her team.',
    painPoints: ['Team coordination', 'Meeting overload', 'Balancing technical and management work'],
    goals: ['Team success', 'Director promotion', 'Mentoring others'],
    preferredChannels: ['Slack', 'LinkedIn', 'Tech blogs']
  },
  {
    id: 'cp_008',
    name: 'Ahmed Hassan',
    age: 34,
    gender: 'male',
    nationality: 'Saudi Arabian',
    ethnicity: 'Arab',
    location: 'Riyadh, Saudi Arabia',
    occupation: 'Entrepreneur',
    industry: 'E-commerce',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'intuitive',
    riskTolerance: 'aggressive',
    buyingMotivation: 'innovation',
    bio: 'Serial entrepreneur with three successful exits. Always looking for the next big opportunity. Values vision and potential over current features.',
    painPoints: ['Finding the right opportunities', 'Scaling quickly', 'Talent acquisition'],
    goals: ['Build regional champion', 'IPO or major exit', 'Industry transformation'],
    preferredChannels: ['WhatsApp', 'Personal network', 'Industry events']
  },
  {
    id: 'cp_009',
    name: 'Emma Thompson',
    age: 31,
    gender: 'female',
    nationality: 'British',
    ethnicity: 'White British',
    location: 'London, UK',
    occupation: 'Strategy Consultant',
    industry: 'Consulting',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 4,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Senior consultant at a Big Four firm. Extremely analytical and evidence-driven. Needs to see clear ROI before recommending any tool to clients.',
    painPoints: ['Client expectations', 'Travel fatigue', 'Work-life balance'],
    goals: ['Make partner', 'Build expertise area', 'Thought leadership'],
    preferredChannels: ['LinkedIn', 'Industry reports', 'Professional networks']
  },
  {
    id: 'cp_010',
    name: 'Carlos Rodriguez',
    age: 28,
    gender: 'male',
    nationality: 'Spanish',
    ethnicity: 'Hispanic European',
    location: 'Barcelona, Spain',
    occupation: 'UX Designer',
    industry: 'Technology',
    incomeLevel: 'medium',
    educationLevel: 'bachelors',
    techComfort: 5,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'Lead UX designer at a growing startup. Passionate about user-centered design. Will immediately notice and critique poor UX in any product.',
    painPoints: ['Stakeholder alignment', 'Research time constraints', 'Design system maintenance'],
    goals: ['Create impactful products', 'Build design team', 'Industry recognition'],
    preferredChannels: ['Dribbble', 'Twitter/X', 'Design podcasts']
  },

  // Age Group: 36-45 (Senior Professionals / Executives)
  {
    id: 'cp_011',
    name: 'Jennifer Williams',
    age: 42,
    gender: 'female',
    nationality: 'American',
    ethnicity: 'African American',
    location: 'New York, USA',
    occupation: 'Chief Marketing Officer',
    industry: 'Consumer Goods',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'collaborative',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'CMO at a Fortune 500 company. Responsible for multi-million dollar marketing budgets. Values proven solutions with strong case studies.',
    painPoints: ['Proving marketing ROI', 'Digital transformation', 'Talent development'],
    goals: ['Brand growth', 'Digital leadership', 'Board position'],
    preferredChannels: ['LinkedIn', 'Industry conferences', 'Executive networks']
  },
  {
    id: 'cp_012',
    name: 'Hiroshi Tanaka',
    age: 45,
    gender: 'male',
    nationality: 'Japanese',
    ethnicity: 'East Asian',
    location: 'Tokyo, Japan',
    occupation: 'VP of Operations',
    industry: 'Manufacturing',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Operations leader at a major manufacturing company. Values efficiency, reliability, and continuous improvement. Skeptical of unproven technologies.',
    painPoints: ['Supply chain complexity', 'Quality control', 'Digital transformation'],
    goals: ['Operational excellence', 'Cost reduction', 'Sustainability'],
    preferredChannels: ['Industry publications', 'Trade shows', 'Professional associations']
  },
  {
    id: 'cp_013',
    name: 'Olga Petrov',
    age: 38,
    gender: 'female',
    nationality: 'Russian',
    ethnicity: 'Eastern European',
    location: 'Moscow, Russia',
    occupation: 'Private Equity Partner',
    industry: 'Finance',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 4,
    decisionStyle: 'analytical',
    riskTolerance: 'aggressive',
    buyingMotivation: 'innovation',
    bio: 'Partner at a PE firm focused on tech investments. Always looking for the next big thing. Values data and market potential over current revenue.',
    painPoints: ['Deal flow', 'Due diligence efficiency', 'Portfolio management'],
    goals: ['Fund returns', 'Market reputation', 'Successful exits'],
    preferredChannels: ['Bloomberg', 'Deal networks', 'Industry events']
  },
  {
    id: 'cp_014',
    name: 'Michael O\'Brien',
    age: 41,
    gender: 'male',
    nationality: 'Irish',
    ethnicity: 'White European',
    location: 'Dublin, Ireland',
    occupation: 'CTO',
    industry: 'Healthcare Tech',
    incomeLevel: 'very_high',
    educationLevel: 'doctorate',
    techComfort: 5,
    decisionStyle: 'analytical',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'CTO at a healthcare technology company. Deep technical background with PhD in computer science. Values security, compliance, and innovation.',
    painPoints: ['Regulatory compliance', 'Legacy system integration', 'Talent competition'],
    goals: ['Technical excellence', 'Product innovation', 'Industry impact'],
    preferredChannels: ['Tech conferences', 'GitHub', 'Research papers']
  },
  {
    id: 'cp_015',
    name: 'Amara Diallo',
    age: 36,
    gender: 'female',
    nationality: 'Senegalese',
    ethnicity: 'West African',
    location: 'Dakar, Senegal',
    occupation: 'NGO Director',
    industry: 'Non-profit',
    incomeLevel: 'medium',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'collaborative',
    riskTolerance: 'conservative',
    buyingMotivation: 'price',
    bio: 'Leads an education-focused NGO. Budget-conscious but impact-driven. Values tools that can demonstrate clear social impact.',
    painPoints: ['Funding constraints', 'Impact measurement', 'Donor management'],
    goals: ['Expand reach', 'Sustainable funding', 'Measurable impact'],
    preferredChannels: ['Email', 'NGO networks', 'WhatsApp']
  },

  // Age Group: 46-55 (Senior Executives / Business Owners)
  {
    id: 'cp_016',
    name: 'Robert Chang',
    age: 52,
    gender: 'male',
    nationality: 'Taiwanese',
    ethnicity: 'East Asian',
    location: 'Taipei, Taiwan',
    occupation: 'CEO',
    industry: 'Electronics',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'quality',
    bio: 'CEO of a mid-sized electronics manufacturer. Focused on digital transformation and global expansion. Values relationships and trust.',
    painPoints: ['Global competition', 'Digital transformation', 'Succession planning'],
    goals: ['Market expansion', 'Innovation leadership', 'Legacy building'],
    preferredChannels: ['Industry associations', 'Personal network', 'Trade shows']
  },
  {
    id: 'cp_017',
    name: 'Sarah Johnson',
    age: 48,
    gender: 'female',
    nationality: 'Australian',
    ethnicity: 'White Australian',
    location: 'Sydney, Australia',
    occupation: 'Managing Director',
    industry: 'Professional Services',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'collaborative',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'MD of a professional services firm. Focused on client relationships and team development. Values proven solutions with strong references.',
    painPoints: ['Client retention', 'Talent management', 'Digital disruption'],
    goals: ['Firm growth', 'Client satisfaction', 'Team development'],
    preferredChannels: ['LinkedIn', 'Industry events', 'Professional networks']
  },
  {
    id: 'cp_018',
    name: 'Mohammed Al-Rashid',
    age: 50,
    gender: 'male',
    nationality: 'Emirati',
    ethnicity: 'Arab',
    location: 'Abu Dhabi, UAE',
    occupation: 'Family Office Director',
    industry: 'Investment',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 2,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'status',
    bio: 'Manages a large family office with diverse investments. Values discretion, quality, and long-term relationships. Prefers premium solutions.',
    painPoints: ['Privacy concerns', 'Generational transition', 'Diversification'],
    goals: ['Wealth preservation', 'Next generation preparation', 'Impact investing'],
    preferredChannels: ['Private banking networks', 'Personal referrals', 'Exclusive events']
  },
  {
    id: 'cp_019',
    name: 'Lisa Mueller',
    age: 46,
    gender: 'female',
    nationality: 'German',
    ethnicity: 'White European',
    location: 'Munich, Germany',
    occupation: 'VP of HR',
    industry: 'Automotive',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'collaborative',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'HR leader at a major automotive company. Focused on talent development and organizational transformation. Values compliance and employee experience.',
    painPoints: ['Talent war', 'Digital skills gap', 'Change management'],
    goals: ['Employer brand', 'Digital HR transformation', 'Diversity and inclusion'],
    preferredChannels: ['HR conferences', 'LinkedIn', 'Professional associations']
  },
  {
    id: 'cp_020',
    name: 'Antonio Silva',
    age: 54,
    gender: 'male',
    nationality: 'Brazilian',
    ethnicity: 'Hispanic',
    location: 'Sao Paulo, Brazil',
    occupation: 'Business Owner',
    industry: 'Retail',
    incomeLevel: 'high',
    educationLevel: 'bachelors',
    techComfort: 2,
    decisionStyle: 'intuitive',
    riskTolerance: 'conservative',
    buyingMotivation: 'convenience',
    bio: 'Owns a chain of retail stores. Traditional businessman adapting to e-commerce. Values simplicity and results over features.',
    painPoints: ['E-commerce competition', 'Technology adoption', 'Economic volatility'],
    goals: ['Business survival', 'Digital presence', 'Family succession'],
    preferredChannels: ['WhatsApp', 'Local business networks', 'Trade associations']
  },

  // Age Group: 56-65 (Pre-retirement / Board Members)
  {
    id: 'cp_021',
    name: 'Patricia Wong',
    age: 58,
    gender: 'female',
    nationality: 'Canadian',
    ethnicity: 'Asian Canadian',
    location: 'Vancouver, Canada',
    occupation: 'Board Director',
    industry: 'Multiple',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Serves on multiple corporate boards. Focused on governance and risk management. Values thorough analysis and proven track records.',
    painPoints: ['Board effectiveness', 'ESG compliance', 'Cyber risk'],
    goals: ['Governance excellence', 'Mentoring next generation', 'Portfolio companies success'],
    preferredChannels: ['Board networks', 'Executive education', 'Industry reports']
  },
  {
    id: 'cp_022',
    name: 'Hans Schneider',
    age: 62,
    gender: 'male',
    nationality: 'Swiss',
    ethnicity: 'White European',
    location: 'Zurich, Switzerland',
    occupation: 'Private Investor',
    industry: 'Investment',
    incomeLevel: 'very_high',
    educationLevel: 'doctorate',
    techComfort: 2,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Retired banker now managing personal investments. Extremely risk-averse and values capital preservation. Prefers established solutions.',
    painPoints: ['Market volatility', 'Technology complexity', 'Finding trustworthy advisors'],
    goals: ['Wealth preservation', 'Philanthropy', 'Family legacy'],
    preferredChannels: ['Private banking', 'Personal advisors', 'Traditional media']
  },
  {
    id: 'cp_023',
    name: 'Yuki Nakamura',
    age: 56,
    gender: 'female',
    nationality: 'Japanese',
    ethnicity: 'East Asian',
    location: 'Osaka, Japan',
    occupation: 'Hospital Administrator',
    industry: 'Healthcare',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 2,
    decisionStyle: 'collaborative',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Runs a major hospital. Focused on patient care and operational efficiency. Values reliability and compliance above all.',
    painPoints: ['Staff shortages', 'Technology integration', 'Regulatory compliance'],
    goals: ['Patient outcomes', 'Operational efficiency', 'Staff satisfaction'],
    preferredChannels: ['Healthcare conferences', 'Professional associations', 'Peer networks']
  },
  {
    id: 'cp_024',
    name: 'George Papadopoulos',
    age: 60,
    gender: 'male',
    nationality: 'Greek',
    ethnicity: 'Mediterranean',
    location: 'Athens, Greece',
    occupation: 'Shipping Executive',
    industry: 'Maritime',
    incomeLevel: 'very_high',
    educationLevel: 'bachelors',
    techComfort: 2,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'convenience',
    bio: 'Senior executive in shipping industry. Traditional industry but open to innovation that proves ROI. Values relationships and trust.',
    painPoints: ['Regulatory changes', 'Environmental compliance', 'Digital transformation'],
    goals: ['Fleet modernization', 'Sustainability', 'Next generation preparation'],
    preferredChannels: ['Industry events', 'Personal network', 'Trade publications']
  },
  {
    id: 'cp_025',
    name: 'Margaret O\'Connor',
    age: 64,
    gender: 'female',
    nationality: 'American',
    ethnicity: 'White American',
    location: 'Boston, USA',
    occupation: 'University Dean',
    industry: 'Education',
    incomeLevel: 'high',
    educationLevel: 'doctorate',
    techComfort: 3,
    decisionStyle: 'collaborative',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Dean of a business school. Focused on educational innovation and student outcomes. Values academic rigor and evidence-based approaches.',
    painPoints: ['Online competition', 'Student recruitment', 'Faculty development'],
    goals: ['Academic excellence', 'Innovation in education', 'Industry partnerships'],
    preferredChannels: ['Academic conferences', 'Peer institutions', 'Research publications']
  },

  // Age Group: 66+ (Retirees / Advisors)
  {
    id: 'cp_026',
    name: 'Richard Thompson',
    age: 68,
    gender: 'male',
    nationality: 'British',
    ethnicity: 'White British',
    location: 'Edinburgh, UK',
    occupation: 'Retired CEO / Advisor',
    industry: 'Advisory',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 2,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Former FTSE 100 CEO now advising startups. Wealth of experience but limited patience for complexity. Values simplicity and results.',
    painPoints: ['Technology learning curve', 'Staying relevant', 'Time management'],
    goals: ['Giving back', 'Staying engaged', 'Supporting entrepreneurs'],
    preferredChannels: ['Personal network', 'Email', 'Face-to-face meetings']
  },
  {
    id: 'cp_027',
    name: 'Mei Lin Chen',
    age: 70,
    gender: 'female',
    nationality: 'Singaporean',
    ethnicity: 'Chinese',
    location: 'Singapore',
    occupation: 'Philanthropist',
    industry: 'Non-profit',
    incomeLevel: 'very_high',
    educationLevel: 'bachelors',
    techComfort: 2,
    decisionStyle: 'intuitive',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Retired businesswoman focused on philanthropy. Values impact and legacy. Prefers personal relationships over digital interactions.',
    painPoints: ['Impact measurement', 'Finding worthy causes', 'Technology complexity'],
    goals: ['Meaningful impact', 'Family involvement', 'Legacy building'],
    preferredChannels: ['Personal network', 'Charity events', 'Family office advisors']
  },
  {
    id: 'cp_028',
    name: 'William Foster',
    age: 72,
    gender: 'male',
    nationality: 'American',
    ethnicity: 'White American',
    location: 'Phoenix, USA',
    occupation: 'Retired Investor',
    industry: 'Investment',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 1,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'convenience',
    bio: 'Retired Wall Street veteran. Skeptical of new technology but open to solutions that simplify his life. Values personal service.',
    painPoints: ['Technology frustration', 'Health management', 'Estate planning'],
    goals: ['Comfortable retirement', 'Family time', 'Health maintenance'],
    preferredChannels: ['Phone calls', 'Personal advisors', 'Traditional mail']
  },

  // Diverse Professional Backgrounds - Continued
  {
    id: 'cp_029',
    name: 'Zara Patel',
    age: 35,
    gender: 'female',
    nationality: 'British Indian',
    ethnicity: 'South Asian',
    location: 'Manchester, UK',
    occupation: 'Data Scientist',
    industry: 'Technology',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 5,
    decisionStyle: 'analytical',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'Lead data scientist at a retail analytics company. Passionate about AI and machine learning. Values tools that are technically sophisticated.',
    painPoints: ['Data quality', 'Stakeholder communication', 'Model deployment'],
    goals: ['Technical leadership', 'Industry impact', 'Research publication'],
    preferredChannels: ['Kaggle', 'Medium', 'Tech conferences']
  },
  {
    id: 'cp_030',
    name: 'Erik Johansson',
    age: 40,
    gender: 'male',
    nationality: 'Swedish',
    ethnicity: 'Scandinavian',
    location: 'Stockholm, Sweden',
    occupation: 'Sustainability Director',
    industry: 'Energy',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 4,
    decisionStyle: 'collaborative',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'Leads sustainability initiatives at an energy company. Passionate about climate action. Values tools that support ESG goals.',
    painPoints: ['Measuring impact', 'Stakeholder alignment', 'Regulatory complexity'],
    goals: ['Carbon neutrality', 'Industry transformation', 'Thought leadership'],
    preferredChannels: ['LinkedIn', 'Sustainability conferences', 'Industry reports']
  },

  // Small Business Owners
  {
    id: 'cp_031',
    name: 'Maria Garcia',
    age: 45,
    gender: 'female',
    nationality: 'Spanish',
    ethnicity: 'Hispanic European',
    location: 'Madrid, Spain',
    occupation: 'Restaurant Owner',
    industry: 'Hospitality',
    incomeLevel: 'medium',
    educationLevel: 'high_school',
    techComfort: 2,
    decisionStyle: 'intuitive',
    riskTolerance: 'conservative',
    buyingMotivation: 'convenience',
    bio: 'Owns a family restaurant for 20 years. Traditional approach but recognizes need for digital presence. Values simplicity above all.',
    painPoints: ['Online presence', 'Staff management', 'Rising costs'],
    goals: ['Business survival', 'Family succession', 'Customer loyalty'],
    preferredChannels: ['WhatsApp', 'Local networks', 'Word of mouth']
  },
  {
    id: 'cp_032',
    name: 'Kwame Asante',
    age: 38,
    gender: 'male',
    nationality: 'Ghanaian',
    ethnicity: 'West African',
    location: 'Accra, Ghana',
    occupation: 'Tech Startup Founder',
    industry: 'Technology',
    incomeLevel: 'medium',
    educationLevel: 'bachelors',
    techComfort: 5,
    decisionStyle: 'intuitive',
    riskTolerance: 'aggressive',
    buyingMotivation: 'innovation',
    bio: 'Building a fintech startup focused on remittances. Resourceful and adaptable. Values tools that work in challenging infrastructure.',
    painPoints: ['Funding access', 'Infrastructure limitations', 'Talent acquisition'],
    goals: ['Product-market fit', 'Series A funding', 'Regional expansion'],
    preferredChannels: ['Twitter/X', 'Startup events', 'WhatsApp groups']
  },
  {
    id: 'cp_033',
    name: 'Anna Kowalski',
    age: 33,
    gender: 'female',
    nationality: 'Polish',
    ethnicity: 'Eastern European',
    location: 'Warsaw, Poland',
    occupation: 'E-commerce Entrepreneur',
    industry: 'Retail',
    incomeLevel: 'medium',
    educationLevel: 'bachelors',
    techComfort: 4,
    decisionStyle: 'analytical',
    riskTolerance: 'moderate',
    buyingMotivation: 'price',
    bio: 'Runs an online fashion store. Data-driven approach to business. Values tools with clear ROI and good customer support.',
    painPoints: ['Competition', 'Customer acquisition cost', 'Inventory management'],
    goals: ['Profitability', 'Brand building', 'International expansion'],
    preferredChannels: ['Facebook', 'E-commerce forums', 'YouTube tutorials']
  },

  // Healthcare Professionals
  {
    id: 'cp_034',
    name: 'Dr. James Obi',
    age: 44,
    gender: 'male',
    nationality: 'Nigerian British',
    ethnicity: 'African',
    location: 'Birmingham, UK',
    occupation: 'Consultant Surgeon',
    industry: 'Healthcare',
    incomeLevel: 'very_high',
    educationLevel: 'doctorate',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Senior surgeon at NHS hospital. Values evidence-based solutions. Limited time for learning new tools but appreciates efficiency gains.',
    painPoints: ['Time pressure', 'Administrative burden', 'Work-life balance'],
    goals: ['Patient outcomes', 'Research contribution', 'Teaching'],
    preferredChannels: ['Medical journals', 'Professional conferences', 'Peer recommendations']
  },
  {
    id: 'cp_035',
    name: 'Dr. Sunita Reddy',
    age: 36,
    gender: 'female',
    nationality: 'Indian',
    ethnicity: 'South Asian',
    location: 'Chennai, India',
    occupation: 'Healthcare Administrator',
    industry: 'Healthcare',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 4,
    decisionStyle: 'collaborative',
    riskTolerance: 'moderate',
    buyingMotivation: 'quality',
    bio: 'Manages a private hospital chain. Focused on operational efficiency and patient experience. Open to technology that improves outcomes.',
    painPoints: ['Staff retention', 'Technology integration', 'Cost management'],
    goals: ['Operational excellence', 'Patient satisfaction', 'Expansion'],
    preferredChannels: ['Healthcare conferences', 'LinkedIn', 'Industry associations']
  },

  // Legal Professionals
  {
    id: 'cp_036',
    name: 'Victoria Chen',
    age: 39,
    gender: 'female',
    nationality: 'American',
    ethnicity: 'Asian American',
    location: 'Los Angeles, USA',
    occupation: 'Corporate Lawyer',
    industry: 'Legal',
    incomeLevel: 'very_high',
    educationLevel: 'professional',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Partner at a major law firm. Extremely detail-oriented and risk-averse. Values tools that enhance accuracy and compliance.',
    painPoints: ['Billable hour pressure', 'Document management', 'Client expectations'],
    goals: ['Partnership growth', 'Work-life balance', 'Client satisfaction'],
    preferredChannels: ['Legal publications', 'Bar associations', 'Peer referrals']
  },
  {
    id: 'cp_037',
    name: 'Omar Khalil',
    age: 47,
    gender: 'male',
    nationality: 'Lebanese',
    ethnicity: 'Arab',
    location: 'Beirut, Lebanon',
    occupation: 'Legal Consultant',
    industry: 'Legal',
    incomeLevel: 'high',
    educationLevel: 'professional',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Independent legal consultant specializing in international trade. Values tools that help navigate complex regulations.',
    painPoints: ['Regulatory complexity', 'Client acquisition', 'Economic instability'],
    goals: ['Practice growth', 'International network', 'Thought leadership'],
    preferredChannels: ['Legal networks', 'Industry events', 'Personal referrals']
  },

  // Creative Professionals
  {
    id: 'cp_038',
    name: 'Isabella Romano',
    age: 29,
    gender: 'female',
    nationality: 'Italian',
    ethnicity: 'Mediterranean',
    location: 'Milan, Italy',
    occupation: 'Fashion Designer',
    industry: 'Fashion',
    incomeLevel: 'medium',
    educationLevel: 'bachelors',
    techComfort: 4,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'Emerging fashion designer with own label. Creative and trend-focused. Values tools that support creative process.',
    painPoints: ['Funding', 'Production scaling', 'Market access'],
    goals: ['Brand recognition', 'Sustainable fashion', 'International presence'],
    preferredChannels: ['Instagram', 'Fashion events', 'Industry contacts']
  },
  {
    id: 'cp_039',
    name: 'David Mensah',
    age: 34,
    gender: 'male',
    nationality: 'Ghanaian British',
    ethnicity: 'African',
    location: 'London, UK',
    occupation: 'Music Producer',
    industry: 'Entertainment',
    incomeLevel: 'medium',
    educationLevel: 'bachelors',
    techComfort: 5,
    decisionStyle: 'intuitive',
    riskTolerance: 'aggressive',
    buyingMotivation: 'innovation',
    bio: 'Independent music producer with growing reputation. Early adopter of new technology. Values creative tools that push boundaries.',
    painPoints: ['Income stability', 'Rights management', 'Industry gatekeepers'],
    goals: ['Hit records', 'Own label', 'Industry recognition'],
    preferredChannels: ['SoundCloud', 'Instagram', 'Industry events']
  },
  {
    id: 'cp_040',
    name: 'Sophie Laurent',
    age: 42,
    gender: 'female',
    nationality: 'French',
    ethnicity: 'White European',
    location: 'Paris, France',
    occupation: 'Art Gallery Director',
    industry: 'Arts',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'quality',
    bio: 'Runs a contemporary art gallery. Values aesthetics and cultural significance. Open to digital tools that enhance art experience.',
    painPoints: ['Artist discovery', 'Digital presence', 'Collector engagement'],
    goals: ['Gallery reputation', 'Artist careers', 'Cultural impact'],
    preferredChannels: ['Art fairs', 'Instagram', 'Collector networks']
  },

  // Education Professionals
  {
    id: 'cp_041',
    name: 'Dr. Rachel Green',
    age: 48,
    gender: 'female',
    nationality: 'American',
    ethnicity: 'White American',
    location: 'Chicago, USA',
    occupation: 'School Principal',
    industry: 'Education',
    incomeLevel: 'medium',
    educationLevel: 'doctorate',
    techComfort: 3,
    decisionStyle: 'collaborative',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Principal of a public high school. Focused on student outcomes and teacher development. Values proven educational tools.',
    painPoints: ['Budget constraints', 'Teacher retention', 'Technology integration'],
    goals: ['Student success', 'School improvement', 'Community engagement'],
    preferredChannels: ['Education conferences', 'Peer networks', 'Professional associations']
  },
  {
    id: 'cp_042',
    name: 'Professor Liu Wei',
    age: 55,
    gender: 'male',
    nationality: 'Chinese',
    ethnicity: 'East Asian',
    location: 'Beijing, China',
    occupation: 'University Professor',
    industry: 'Education',
    incomeLevel: 'high',
    educationLevel: 'doctorate',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Professor of economics at a top university. Values academic rigor and research quality. Skeptical of unproven tools.',
    painPoints: ['Research funding', 'Publication pressure', 'Student engagement'],
    goals: ['Research impact', 'Student development', 'International collaboration'],
    preferredChannels: ['Academic journals', 'Conferences', 'Research networks']
  },

  // Government / Public Sector
  {
    id: 'cp_043',
    name: 'Sarah Al-Mahmoud',
    age: 41,
    gender: 'female',
    nationality: 'Qatari',
    ethnicity: 'Arab',
    location: 'Doha, Qatar',
    occupation: 'Government Director',
    industry: 'Government',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'collaborative',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Director at a government ministry. Focused on digital transformation and citizen services. Values security and compliance.',
    painPoints: ['Bureaucracy', 'Technology adoption', 'Stakeholder alignment'],
    goals: ['Digital government', 'Citizen satisfaction', 'Regional leadership'],
    preferredChannels: ['Government networks', 'International conferences', 'Consulting firms']
  },
  {
    id: 'cp_044',
    name: 'Thomas Anderson',
    age: 52,
    gender: 'male',
    nationality: 'American',
    ethnicity: 'White American',
    location: 'Washington DC, USA',
    occupation: 'Policy Advisor',
    industry: 'Government',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Senior policy advisor in federal government. Values evidence-based policy making. Needs tools that support rigorous analysis.',
    painPoints: ['Political complexity', 'Data access', 'Stakeholder management'],
    goals: ['Policy impact', 'Bipartisan solutions', 'Public service'],
    preferredChannels: ['Think tanks', 'Policy publications', 'Professional networks']
  },

  // Real Estate
  {
    id: 'cp_045',
    name: 'Raj Malhotra',
    age: 46,
    gender: 'male',
    nationality: 'Indian',
    ethnicity: 'South Asian',
    location: 'Mumbai, India',
    occupation: 'Real Estate Developer',
    industry: 'Real Estate',
    incomeLevel: 'very_high',
    educationLevel: 'bachelors',
    techComfort: 3,
    decisionStyle: 'intuitive',
    riskTolerance: 'aggressive',
    buyingMotivation: 'convenience',
    bio: 'Major real estate developer with projects across India. Values relationships and market timing. Open to tech that speeds decisions.',
    painPoints: ['Regulatory approvals', 'Market volatility', 'Project management'],
    goals: ['Portfolio growth', 'Premium positioning', 'International expansion'],
    preferredChannels: ['Industry events', 'Personal network', 'Business media']
  },
  {
    id: 'cp_046',
    name: 'Michelle Brown',
    age: 38,
    gender: 'female',
    nationality: 'American',
    ethnicity: 'African American',
    location: 'Atlanta, USA',
    occupation: 'Real Estate Agent',
    industry: 'Real Estate',
    incomeLevel: 'high',
    educationLevel: 'bachelors',
    techComfort: 4,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'convenience',
    bio: 'Top-performing real estate agent. Values tools that help close deals faster. Customer relationship focused.',
    painPoints: ['Lead generation', 'Market competition', 'Time management'],
    goals: ['Sales growth', 'Team building', 'Market leadership'],
    preferredChannels: ['Zillow', 'Instagram', 'Local networking']
  },

  // Diverse Age and Background Mix - Continued
  {
    id: 'cp_047',
    name: 'Yusuf Ibrahim',
    age: 27,
    gender: 'male',
    nationality: 'Turkish',
    ethnicity: 'Middle Eastern',
    location: 'Istanbul, Turkey',
    occupation: 'Digital Marketer',
    industry: 'Marketing',
    incomeLevel: 'medium',
    educationLevel: 'bachelors',
    techComfort: 5,
    decisionStyle: 'analytical',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'Digital marketing specialist at an agency. Data-driven and always testing new tools. Values measurable results.',
    painPoints: ['Client expectations', 'Platform changes', 'Proving ROI'],
    goals: ['Agency growth', 'Thought leadership', 'International clients'],
    preferredChannels: ['Twitter/X', 'Marketing blogs', 'Online courses']
  },
  {
    id: 'cp_048',
    name: 'Nina Volkov',
    age: 31,
    gender: 'female',
    nationality: 'Ukrainian',
    ethnicity: 'Eastern European',
    location: 'Kyiv, Ukraine',
    occupation: 'Product Manager',
    industry: 'Technology',
    incomeLevel: 'medium',
    educationLevel: 'masters',
    techComfort: 5,
    decisionStyle: 'collaborative',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'Product manager at a tech company. User-focused and data-driven. Values tools that improve product development process.',
    painPoints: ['Stakeholder alignment', 'Resource constraints', 'Market uncertainty'],
    goals: ['Product success', 'Career growth', 'Industry impact'],
    preferredChannels: ['Product Hunt', 'LinkedIn', 'Tech podcasts']
  },
  {
    id: 'cp_049',
    name: 'Chen Xiaoming',
    age: 43,
    gender: 'male',
    nationality: 'Chinese',
    ethnicity: 'East Asian',
    location: 'Shanghai, China',
    occupation: 'Supply Chain Director',
    industry: 'Manufacturing',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Manages global supply chain for a major manufacturer. Values reliability and efficiency. Needs proven solutions.',
    painPoints: ['Supply chain disruption', 'Cost pressure', 'Sustainability requirements'],
    goals: ['Operational excellence', 'Risk mitigation', 'Digital transformation'],
    preferredChannels: ['Industry conferences', 'Professional networks', 'Trade publications']
  },
  {
    id: 'cp_050',
    name: 'Adeola Adeyemi',
    age: 35,
    gender: 'female',
    nationality: 'Nigerian',
    ethnicity: 'West African',
    location: 'Lagos, Nigeria',
    occupation: 'HR Director',
    industry: 'Telecommunications',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 4,
    decisionStyle: 'collaborative',
    riskTolerance: 'moderate',
    buyingMotivation: 'quality',
    bio: 'HR leader at a major telecom company. Focused on talent development and employee experience. Values tools that improve HR processes.',
    painPoints: ['Talent retention', 'Skills gap', 'Digital HR transformation'],
    goals: ['Employer brand', 'HR innovation', 'Employee engagement'],
    preferredChannels: ['LinkedIn', 'HR conferences', 'Professional associations']
  },

  // Additional Diverse Personas (51-100)
  {
    id: 'cp_051',
    name: 'Alexander Petrov',
    age: 49,
    gender: 'male',
    nationality: 'Bulgarian',
    ethnicity: 'Eastern European',
    location: 'Sofia, Bulgaria',
    occupation: 'IT Director',
    industry: 'Financial Services',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 5,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'IT leader at a regional bank. Focused on security and compliance. Values proven enterprise solutions.',
    painPoints: ['Legacy systems', 'Cybersecurity', 'Regulatory compliance'],
    goals: ['Digital transformation', 'Security excellence', 'Cost optimization'],
    preferredChannels: ['IT conferences', 'Vendor briefings', 'Peer networks']
  },
  {
    id: 'cp_052',
    name: 'Lucia Fernandez',
    age: 28,
    gender: 'female',
    nationality: 'Colombian',
    ethnicity: 'Hispanic',
    location: 'Bogota, Colombia',
    occupation: 'Social Media Manager',
    industry: 'Marketing',
    incomeLevel: 'medium',
    educationLevel: 'bachelors',
    techComfort: 5,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'Manages social media for multiple brands. Creative and trend-aware. Values tools that save time and boost engagement.',
    painPoints: ['Content creation pressure', 'Algorithm changes', 'Measuring ROI'],
    goals: ['Viral campaigns', 'Agency ownership', 'Industry recognition'],
    preferredChannels: ['TikTok', 'Instagram', 'Twitter/X']
  },
  {
    id: 'cp_053',
    name: 'Takeshi Yamamoto',
    age: 57,
    gender: 'male',
    nationality: 'Japanese',
    ethnicity: 'East Asian',
    location: 'Nagoya, Japan',
    occupation: 'Factory Manager',
    industry: 'Automotive',
    incomeLevel: 'high',
    educationLevel: 'bachelors',
    techComfort: 2,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Manages a major automotive parts factory. Focused on quality and efficiency. Values continuous improvement.',
    painPoints: ['Labor shortage', 'Quality standards', 'Automation'],
    goals: ['Zero defects', 'Productivity improvement', 'Team development'],
    preferredChannels: ['Industry associations', 'Trade shows', 'Supplier networks']
  },
  {
    id: 'cp_054',
    name: 'Fatou Diop',
    age: 32,
    gender: 'female',
    nationality: 'Senegalese',
    ethnicity: 'West African',
    location: 'Dakar, Senegal',
    occupation: 'Microfinance Manager',
    industry: 'Financial Services',
    incomeLevel: 'medium',
    educationLevel: 'masters',
    techComfort: 4,
    decisionStyle: 'collaborative',
    riskTolerance: 'moderate',
    buyingMotivation: 'price',
    bio: 'Manages microfinance operations. Focused on financial inclusion. Values affordable solutions that work in low-resource settings.',
    painPoints: ['Infrastructure limitations', 'Default rates', 'Scaling challenges'],
    goals: ['Financial inclusion', 'Sustainable growth', 'Social impact'],
    preferredChannels: ['Microfinance networks', 'WhatsApp', 'Development conferences']
  },
  {
    id: 'cp_055',
    name: 'Henrik Nielsen',
    age: 44,
    gender: 'male',
    nationality: 'Danish',
    ethnicity: 'Scandinavian',
    location: 'Copenhagen, Denmark',
    occupation: 'Renewable Energy CEO',
    industry: 'Energy',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 4,
    decisionStyle: 'collaborative',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'Leads a wind energy company. Passionate about sustainability. Values innovation that advances clean energy.',
    painPoints: ['Regulatory uncertainty', 'Grid integration', 'Competition'],
    goals: ['Market leadership', 'Carbon impact', 'Global expansion'],
    preferredChannels: ['Energy conferences', 'LinkedIn', 'Industry publications']
  },
  {
    id: 'cp_056',
    name: 'Rashida Khan',
    age: 37,
    gender: 'female',
    nationality: 'Pakistani British',
    ethnicity: 'South Asian',
    location: 'Leeds, UK',
    occupation: 'Accountant',
    industry: 'Professional Services',
    incomeLevel: 'high',
    educationLevel: 'professional',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Senior accountant at a mid-sized firm. Values accuracy and compliance. Needs tools that integrate with existing systems.',
    painPoints: ['Regulatory changes', 'Client management', 'Work-life balance'],
    goals: ['Partnership track', 'Client growth', 'Professional development'],
    preferredChannels: ['Professional associations', 'LinkedIn', 'Industry publications']
  },
  {
    id: 'cp_057',
    name: 'Juan Pablo Morales',
    age: 26,
    gender: 'male',
    nationality: 'Chilean',
    ethnicity: 'Hispanic',
    location: 'Santiago, Chile',
    occupation: 'Startup Founder',
    industry: 'Technology',
    incomeLevel: 'low',
    educationLevel: 'bachelors',
    techComfort: 5,
    decisionStyle: 'intuitive',
    riskTolerance: 'aggressive',
    buyingMotivation: 'price',
    bio: 'Building an edtech startup. Bootstrapped and resourceful. Values free or low-cost tools that punch above their weight.',
    painPoints: ['Funding', 'Market validation', 'Team building'],
    goals: ['Product-market fit', 'Seed funding', 'Regional expansion'],
    preferredChannels: ['Twitter/X', 'Startup events', 'WhatsApp groups']
  },
  {
    id: 'cp_058',
    name: 'Ingrid Bergstrom',
    age: 51,
    gender: 'female',
    nationality: 'Swedish',
    ethnicity: 'Scandinavian',
    location: 'Gothenburg, Sweden',
    occupation: 'Procurement Director',
    industry: 'Manufacturing',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Manages procurement for a major manufacturer. Values supplier relationships and sustainability. Needs proven solutions.',
    painPoints: ['Supply chain risk', 'Sustainability requirements', 'Cost pressure'],
    goals: ['Sustainable supply chain', 'Cost reduction', 'Supplier innovation'],
    preferredChannels: ['Industry conferences', 'Supplier networks', 'Professional associations']
  },
  {
    id: 'cp_059',
    name: 'Dmitri Sokolov',
    age: 33,
    gender: 'male',
    nationality: 'Russian',
    ethnicity: 'Eastern European',
    location: 'Saint Petersburg, Russia',
    occupation: 'Game Developer',
    industry: 'Gaming',
    incomeLevel: 'medium',
    educationLevel: 'bachelors',
    techComfort: 5,
    decisionStyle: 'intuitive',
    riskTolerance: 'aggressive',
    buyingMotivation: 'innovation',
    bio: 'Indie game developer with cult following. Creative and technically skilled. Values tools that enhance game development.',
    painPoints: ['Marketing', 'Monetization', 'Platform fragmentation'],
    goals: ['Hit game', 'Studio growth', 'Creative freedom'],
    preferredChannels: ['Discord', 'Reddit', 'Game dev conferences']
  },
  {
    id: 'cp_060',
    name: 'Amina Yusuf',
    age: 40,
    gender: 'female',
    nationality: 'Kenyan',
    ethnicity: 'East African',
    location: 'Nairobi, Kenya',
    occupation: 'NGO Program Director',
    industry: 'Non-profit',
    incomeLevel: 'medium',
    educationLevel: 'masters',
    techComfort: 4,
    decisionStyle: 'collaborative',
    riskTolerance: 'conservative',
    buyingMotivation: 'price',
    bio: 'Leads health programs across East Africa. Impact-focused and resource-conscious. Values tools that demonstrate outcomes.',
    painPoints: ['Funding constraints', 'Impact measurement', 'Coordination challenges'],
    goals: ['Health outcomes', 'Sustainable programs', 'Policy influence'],
    preferredChannels: ['Development networks', 'WhatsApp', 'Conferences']
  },

  // More diverse personas to reach 100
  {
    id: 'cp_061',
    name: 'Pierre Dubois',
    age: 59,
    gender: 'male',
    nationality: 'French',
    ethnicity: 'White European',
    location: 'Lyon, France',
    occupation: 'Winery Owner',
    industry: 'Agriculture',
    incomeLevel: 'high',
    educationLevel: 'bachelors',
    techComfort: 2,
    decisionStyle: 'intuitive',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Third-generation winery owner. Traditional approach but recognizes need for modernization. Values quality and heritage.',
    painPoints: ['Climate change', 'Market competition', 'Succession planning'],
    goals: ['Quality maintenance', 'Export growth', 'Family legacy'],
    preferredChannels: ['Wine associations', 'Trade shows', 'Personal network']
  },
  {
    id: 'cp_062',
    name: 'Ayesha Begum',
    age: 30,
    gender: 'female',
    nationality: 'Bangladeshi',
    ethnicity: 'South Asian',
    location: 'Dhaka, Bangladesh',
    occupation: 'Garment Factory Manager',
    industry: 'Manufacturing',
    incomeLevel: 'medium',
    educationLevel: 'bachelors',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'price',
    bio: 'Manages a garment factory serving international brands. Focused on compliance and efficiency. Values affordable solutions.',
    painPoints: ['Compliance requirements', 'Labor management', 'Margin pressure'],
    goals: ['Compliance excellence', 'Productivity improvement', 'Career growth'],
    preferredChannels: ['Industry associations', 'WhatsApp', 'Trade shows']
  },
  {
    id: 'cp_063',
    name: 'Sven Eriksson',
    age: 47,
    gender: 'male',
    nationality: 'Norwegian',
    ethnicity: 'Scandinavian',
    location: 'Oslo, Norway',
    occupation: 'Shipping Executive',
    industry: 'Maritime',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'Executive at a major shipping company. Focused on sustainability and efficiency. Open to innovation that reduces emissions.',
    painPoints: ['Environmental regulations', 'Fuel costs', 'Digital transformation'],
    goals: ['Green shipping', 'Operational efficiency', 'Industry leadership'],
    preferredChannels: ['Maritime conferences', 'Industry publications', 'Professional networks']
  },
  {
    id: 'cp_064',
    name: 'Thandiwe Ndlovu',
    age: 36,
    gender: 'female',
    nationality: 'South African',
    ethnicity: 'African',
    location: 'Johannesburg, South Africa',
    occupation: 'Mining Engineer',
    industry: 'Mining',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 4,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Senior engineer at a mining company. Focused on safety and efficiency. Values proven technologies.',
    painPoints: ['Safety requirements', 'Environmental compliance', 'Operational efficiency'],
    goals: ['Zero harm', 'Productivity improvement', 'Career advancement'],
    preferredChannels: ['Mining conferences', 'Professional associations', 'Technical publications']
  },
  {
    id: 'cp_065',
    name: 'Kenji Watanabe',
    age: 29,
    gender: 'male',
    nationality: 'Japanese',
    ethnicity: 'East Asian',
    location: 'Tokyo, Japan',
    occupation: 'Venture Capitalist',
    industry: 'Finance',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 5,
    decisionStyle: 'analytical',
    riskTolerance: 'aggressive',
    buyingMotivation: 'innovation',
    bio: 'Associate at a tech-focused VC firm. Always looking for the next big thing. Values innovation and market potential.',
    painPoints: ['Deal flow', 'Due diligence', 'Portfolio support'],
    goals: ['Successful exits', 'Fund returns', 'Industry reputation'],
    preferredChannels: ['Tech events', 'Twitter/X', 'Startup networks']
  },
  {
    id: 'cp_066',
    name: 'Gabriela Santos',
    age: 43,
    gender: 'female',
    nationality: 'Brazilian',
    ethnicity: 'Hispanic',
    location: 'Rio de Janeiro, Brazil',
    occupation: 'Tourism Director',
    industry: 'Hospitality',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'collaborative',
    riskTolerance: 'moderate',
    buyingMotivation: 'quality',
    bio: 'Leads tourism development for a major destination. Focused on sustainable tourism. Values tools that enhance visitor experience.',
    painPoints: ['Seasonality', 'Infrastructure', 'Sustainability'],
    goals: ['Sustainable tourism', 'Economic impact', 'Global recognition'],
    preferredChannels: ['Tourism conferences', 'Government networks', 'Industry associations']
  },
  {
    id: 'cp_067',
    name: 'Abdul Rahman',
    age: 54,
    gender: 'male',
    nationality: 'Malaysian',
    ethnicity: 'Southeast Asian',
    location: 'Kuala Lumpur, Malaysia',
    occupation: 'Islamic Finance Director',
    industry: 'Financial Services',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Director at an Islamic bank. Focused on Shariah compliance and innovation. Values solutions that meet religious requirements.',
    painPoints: ['Shariah compliance', 'Product innovation', 'Market competition'],
    goals: ['Market leadership', 'Product innovation', 'Regional expansion'],
    preferredChannels: ['Islamic finance conferences', 'Industry associations', 'Professional networks']
  },
  {
    id: 'cp_068',
    name: 'Elena Popescu',
    age: 31,
    gender: 'female',
    nationality: 'Romanian',
    ethnicity: 'Eastern European',
    location: 'Bucharest, Romania',
    occupation: 'Cybersecurity Analyst',
    industry: 'Technology',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 5,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Cybersecurity specialist at a financial institution. Highly technical and security-focused. Values robust, proven solutions.',
    painPoints: ['Threat landscape', 'Compliance requirements', 'Talent shortage'],
    goals: ['Security excellence', 'Career growth', 'Industry recognition'],
    preferredChannels: ['Security conferences', 'Technical forums', 'Professional certifications']
  },
  {
    id: 'cp_069',
    name: 'Kofi Mensah',
    age: 48,
    gender: 'male',
    nationality: 'Ghanaian',
    ethnicity: 'West African',
    location: 'Accra, Ghana',
    occupation: 'Cocoa Exporter',
    industry: 'Agriculture',
    incomeLevel: 'high',
    educationLevel: 'bachelors',
    techComfort: 3,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'convenience',
    bio: 'Runs a cocoa export business. Focused on quality and sustainability. Values tools that simplify international trade.',
    painPoints: ['Price volatility', 'Certification requirements', 'Logistics'],
    goals: ['Premium positioning', 'Direct trade', 'Sustainability certification'],
    preferredChannels: ['Trade associations', 'WhatsApp', 'Industry events']
  },
  {
    id: 'cp_070',
    name: 'Natasha Ivanova',
    age: 35,
    gender: 'female',
    nationality: 'Russian',
    ethnicity: 'Eastern European',
    location: 'Moscow, Russia',
    occupation: 'Fashion Buyer',
    industry: 'Retail',
    incomeLevel: 'high',
    educationLevel: 'bachelors',
    techComfort: 4,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'Fashion buyer for a luxury department store. Trend-focused and relationship-driven. Values tools that predict trends.',
    painPoints: ['Trend prediction', 'Inventory management', 'Supplier relationships'],
    goals: ['Sales growth', 'Trend leadership', 'Brand partnerships'],
    preferredChannels: ['Fashion weeks', 'Instagram', 'Industry contacts']
  },

  // Final 30 personas to complete 100
  {
    id: 'cp_071',
    name: 'Benjamin Osei',
    age: 41,
    gender: 'male',
    nationality: 'Ghanaian British',
    ethnicity: 'African',
    location: 'Bristol, UK',
    occupation: 'Architect',
    industry: 'Construction',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 4,
    decisionStyle: 'collaborative',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'Partner at an architecture firm. Focused on sustainable design. Values tools that enhance creative process.',
    painPoints: ['Project complexity', 'Client expectations', 'Sustainability requirements'],
    goals: ['Design excellence', 'Sustainability leadership', 'Firm growth'],
    preferredChannels: ['Architecture publications', 'LinkedIn', 'Design conferences']
  },
  {
    id: 'cp_072',
    name: 'Mei Ling Tan',
    age: 27,
    gender: 'female',
    nationality: 'Singaporean',
    ethnicity: 'Chinese',
    location: 'Singapore',
    occupation: 'Investment Analyst',
    industry: 'Finance',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 5,
    decisionStyle: 'analytical',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'Analyst at an asset management firm. Data-driven and detail-oriented. Values tools that provide analytical edge.',
    painPoints: ['Information overload', 'Competition', 'Work-life balance'],
    goals: ['Portfolio performance', 'Career advancement', 'CFA completion'],
    preferredChannels: ['Bloomberg', 'LinkedIn', 'Finance podcasts']
  },
  {
    id: 'cp_073',
    name: 'Carlos Mendez',
    age: 52,
    gender: 'male',
    nationality: 'Peruvian',
    ethnicity: 'Hispanic',
    location: 'Lima, Peru',
    occupation: 'Mining Executive',
    industry: 'Mining',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Executive at a major mining company. Focused on operational excellence and community relations. Values proven solutions.',
    painPoints: ['Community relations', 'Environmental compliance', 'Operational efficiency'],
    goals: ['Sustainable mining', 'Community development', 'Operational excellence'],
    preferredChannels: ['Mining conferences', 'Industry associations', 'Government relations']
  },
  {
    id: 'cp_074',
    name: 'Aiko Suzuki',
    age: 34,
    gender: 'female',
    nationality: 'Japanese',
    ethnicity: 'East Asian',
    location: 'Kyoto, Japan',
    occupation: 'Hotel Manager',
    industry: 'Hospitality',
    incomeLevel: 'medium',
    educationLevel: 'bachelors',
    techComfort: 3,
    decisionStyle: 'collaborative',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Manages a traditional ryokan. Balances tradition with modern expectations. Values tools that enhance guest experience.',
    painPoints: ['Staff shortage', 'Online presence', 'Balancing tradition and modernity'],
    goals: ['Guest satisfaction', 'Cultural preservation', 'Sustainable tourism'],
    preferredChannels: ['Hospitality associations', 'Travel platforms', 'Local networks']
  },
  {
    id: 'cp_075',
    name: 'Oluwaseun Adebayo',
    age: 29,
    gender: 'male',
    nationality: 'Nigerian',
    ethnicity: 'West African',
    location: 'Abuja, Nigeria',
    occupation: 'Policy Analyst',
    industry: 'Government',
    incomeLevel: 'medium',
    educationLevel: 'masters',
    techComfort: 4,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Policy analyst at a government ministry. Focused on economic development. Values evidence-based tools.',
    painPoints: ['Data availability', 'Policy implementation', 'Stakeholder alignment'],
    goals: ['Policy impact', 'Career advancement', 'International exposure'],
    preferredChannels: ['Policy networks', 'Academic publications', 'Development conferences']
  },
  {
    id: 'cp_076',
    name: 'Valentina Rossi',
    age: 45,
    gender: 'female',
    nationality: 'Italian',
    ethnicity: 'Mediterranean',
    location: 'Rome, Italy',
    occupation: 'Museum Director',
    industry: 'Arts',
    incomeLevel: 'high',
    educationLevel: 'doctorate',
    techComfort: 3,
    decisionStyle: 'collaborative',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Directs a major art museum. Focused on preservation and public engagement. Values tools that enhance cultural access.',
    painPoints: ['Funding', 'Digital engagement', 'Preservation'],
    goals: ['Cultural impact', 'Visitor engagement', 'Collection preservation'],
    preferredChannels: ['Museum networks', 'Cultural events', 'Academic circles']
  },
  {
    id: 'cp_077',
    name: 'Tariq Al-Farsi',
    age: 38,
    gender: 'male',
    nationality: 'Omani',
    ethnicity: 'Arab',
    location: 'Muscat, Oman',
    occupation: 'Oil and Gas Engineer',
    industry: 'Energy',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 4,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Senior engineer at a national oil company. Focused on efficiency and safety. Values proven industrial solutions.',
    painPoints: ['Energy transition', 'Operational efficiency', 'Safety compliance'],
    goals: ['Operational excellence', 'Career advancement', 'Industry contribution'],
    preferredChannels: ['Energy conferences', 'Professional associations', 'Technical publications']
  },
  {
    id: 'cp_078',
    name: 'Grace Okonkwo',
    age: 33,
    gender: 'female',
    nationality: 'Nigerian',
    ethnicity: 'West African',
    location: 'Port Harcourt, Nigeria',
    occupation: 'Entrepreneur',
    industry: 'Agriculture',
    incomeLevel: 'medium',
    educationLevel: 'bachelors',
    techComfort: 4,
    decisionStyle: 'intuitive',
    riskTolerance: 'aggressive',
    buyingMotivation: 'innovation',
    bio: 'Building an agritech startup. Passionate about food security. Values tools that work in challenging environments.',
    painPoints: ['Infrastructure', 'Funding', 'Market access'],
    goals: ['Food security impact', 'Business growth', 'Farmer empowerment'],
    preferredChannels: ['Agritech events', 'WhatsApp', 'Development networks']
  },
  {
    id: 'cp_079',
    name: 'Lars Hansen',
    age: 56,
    gender: 'male',
    nationality: 'Danish',
    ethnicity: 'Scandinavian',
    location: 'Aarhus, Denmark',
    occupation: 'Pharmaceutical Executive',
    industry: 'Healthcare',
    incomeLevel: 'very_high',
    educationLevel: 'doctorate',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Executive at a pharmaceutical company. Focused on R&D and compliance. Values proven, compliant solutions.',
    painPoints: ['Regulatory complexity', 'R&D costs', 'Market access'],
    goals: ['Drug development', 'Market expansion', 'Compliance excellence'],
    preferredChannels: ['Pharma conferences', 'Regulatory networks', 'Industry publications']
  },
  {
    id: 'cp_080',
    name: 'Priscilla Owusu',
    age: 28,
    gender: 'female',
    nationality: 'Ghanaian',
    ethnicity: 'West African',
    location: 'Kumasi, Ghana',
    occupation: 'Teacher',
    industry: 'Education',
    incomeLevel: 'low',
    educationLevel: 'bachelors',
    techComfort: 3,
    decisionStyle: 'collaborative',
    riskTolerance: 'conservative',
    buyingMotivation: 'price',
    bio: 'High school teacher passionate about education. Resource-constrained but innovative. Values affordable educational tools.',
    painPoints: ['Resource limitations', 'Large class sizes', 'Technology access'],
    goals: ['Student success', 'Professional development', 'Educational innovation'],
    preferredChannels: ['Teacher networks', 'WhatsApp', 'Educational platforms']
  },
  {
    id: 'cp_081',
    name: 'Viktor Novak',
    age: 42,
    gender: 'male',
    nationality: 'Czech',
    ethnicity: 'Eastern European',
    location: 'Prague, Czech Republic',
    occupation: 'Brewery Owner',
    industry: 'Food and Beverage',
    incomeLevel: 'high',
    educationLevel: 'bachelors',
    techComfort: 3,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'quality',
    bio: 'Owns a craft brewery. Balances tradition with innovation. Values tools that enhance quality without compromising craft.',
    painPoints: ['Competition', 'Distribution', 'Scaling while maintaining quality'],
    goals: ['Quality excellence', 'Market expansion', 'Brand recognition'],
    preferredChannels: ['Brewing associations', 'Trade shows', 'Local networks']
  },
  {
    id: 'cp_082',
    name: 'Ananya Krishnan',
    age: 31,
    gender: 'female',
    nationality: 'Indian',
    ethnicity: 'South Asian',
    location: 'Hyderabad, India',
    occupation: 'Biotech Researcher',
    industry: 'Healthcare',
    incomeLevel: 'medium',
    educationLevel: 'doctorate',
    techComfort: 5,
    decisionStyle: 'analytical',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'Research scientist at a biotech company. Focused on drug discovery. Values cutting-edge research tools.',
    painPoints: ['Research funding', 'Publication pressure', 'Technology access'],
    goals: ['Scientific breakthrough', 'Career advancement', 'Industry impact'],
    preferredChannels: ['Scientific journals', 'Research conferences', 'Academic networks']
  },
  {
    id: 'cp_083',
    name: 'Mohammed Al-Hashimi',
    age: 49,
    gender: 'male',
    nationality: 'Iraqi',
    ethnicity: 'Arab',
    location: 'Baghdad, Iraq',
    occupation: 'Construction Company Owner',
    industry: 'Construction',
    incomeLevel: 'high',
    educationLevel: 'bachelors',
    techComfort: 2,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'convenience',
    bio: 'Owns a construction company. Focused on rebuilding infrastructure. Values practical, reliable solutions.',
    painPoints: ['Security', 'Supply chain', 'Skilled labor'],
    goals: ['Business growth', 'Infrastructure contribution', 'Family legacy'],
    preferredChannels: ['Business networks', 'Personal contacts', 'Trade associations']
  },
  {
    id: 'cp_084',
    name: 'Sarah Johansson',
    age: 36,
    gender: 'female',
    nationality: 'Swedish',
    ethnicity: 'Scandinavian',
    location: 'Malmo, Sweden',
    occupation: 'Sustainability Consultant',
    industry: 'Consulting',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 4,
    decisionStyle: 'collaborative',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'Helps companies with sustainability transformation. Values tools that measure and improve environmental impact.',
    painPoints: ['Greenwashing', 'Measurement complexity', 'Client commitment'],
    goals: ['Environmental impact', 'Thought leadership', 'Business growth'],
    preferredChannels: ['Sustainability conferences', 'LinkedIn', 'Industry reports']
  },
  {
    id: 'cp_085',
    name: 'Chen Wei',
    age: 44,
    gender: 'male',
    nationality: 'Chinese',
    ethnicity: 'East Asian',
    location: 'Shenzhen, China',
    occupation: 'Electronics Manufacturer',
    industry: 'Manufacturing',
    incomeLevel: 'very_high',
    educationLevel: 'bachelors',
    techComfort: 4,
    decisionStyle: 'analytical',
    riskTolerance: 'moderate',
    buyingMotivation: 'quality',
    bio: 'Owns an electronics manufacturing company. Focused on quality and efficiency. Values tools that improve production.',
    painPoints: ['Trade tensions', 'Quality control', 'Labor costs'],
    goals: ['Quality leadership', 'Automation', 'Market diversification'],
    preferredChannels: ['Trade shows', 'Industry associations', 'Business networks']
  },
  {
    id: 'cp_086',
    name: 'Fatima Benali',
    age: 39,
    gender: 'female',
    nationality: 'Moroccan',
    ethnicity: 'North African',
    location: 'Casablanca, Morocco',
    occupation: 'Textile Exporter',
    industry: 'Manufacturing',
    incomeLevel: 'high',
    educationLevel: 'bachelors',
    techComfort: 3,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'convenience',
    bio: 'Runs a textile export business. Focused on quality and sustainability. Values tools that simplify international trade.',
    painPoints: ['Competition', 'Sustainability requirements', 'Logistics'],
    goals: ['Premium positioning', 'European market growth', 'Sustainability certification'],
    preferredChannels: ['Trade fairs', 'Industry associations', 'WhatsApp']
  },
  {
    id: 'cp_087',
    name: 'Robert Kimani',
    age: 47,
    gender: 'male',
    nationality: 'Kenyan',
    ethnicity: 'East African',
    location: 'Mombasa, Kenya',
    occupation: 'Port Authority Director',
    industry: 'Logistics',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Manages port operations. Focused on efficiency and regional trade. Values proven logistics solutions.',
    painPoints: ['Infrastructure', 'Efficiency', 'Regional competition'],
    goals: ['Operational excellence', 'Regional hub status', 'Digital transformation'],
    preferredChannels: ['Logistics conferences', 'Government networks', 'Industry associations']
  },
  {
    id: 'cp_088',
    name: 'Maria Antonova',
    age: 32,
    gender: 'female',
    nationality: 'Bulgarian',
    ethnicity: 'Eastern European',
    location: 'Plovdiv, Bulgaria',
    occupation: 'Wine Exporter',
    industry: 'Agriculture',
    incomeLevel: 'medium',
    educationLevel: 'bachelors',
    techComfort: 4,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'innovation',
    bio: 'Building a wine export business. Focused on quality and branding. Values tools that help reach international markets.',
    painPoints: ['Brand recognition', 'Distribution', 'Competition'],
    goals: ['International presence', 'Premium positioning', 'Sustainable growth'],
    preferredChannels: ['Wine events', 'Social media', 'Trade networks']
  },
  {
    id: 'cp_089',
    name: 'Nguyen Van Minh',
    age: 53,
    gender: 'male',
    nationality: 'Vietnamese',
    ethnicity: 'Southeast Asian',
    location: 'Ho Chi Minh City, Vietnam',
    occupation: 'Furniture Manufacturer',
    industry: 'Manufacturing',
    incomeLevel: 'high',
    educationLevel: 'bachelors',
    techComfort: 2,
    decisionStyle: 'intuitive',
    riskTolerance: 'conservative',
    buyingMotivation: 'convenience',
    bio: 'Owns a furniture manufacturing company. Focused on quality and export. Values practical solutions.',
    painPoints: ['Raw material costs', 'Quality control', 'International standards'],
    goals: ['Export growth', 'Quality improvement', 'Sustainability'],
    preferredChannels: ['Trade fairs', 'Industry associations', 'Business networks']
  },
  {
    id: 'cp_090',
    name: 'Leila Ahmadi',
    age: 35,
    gender: 'female',
    nationality: 'Iranian Canadian',
    ethnicity: 'Middle Eastern',
    location: 'Toronto, Canada',
    occupation: 'Immigration Lawyer',
    industry: 'Legal',
    incomeLevel: 'high',
    educationLevel: 'professional',
    techComfort: 4,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Immigration lawyer with own practice. Focused on client service. Values tools that improve case management.',
    painPoints: ['Regulatory changes', 'Case volume', 'Client communication'],
    goals: ['Practice growth', 'Client satisfaction', 'Work-life balance'],
    preferredChannels: ['Legal associations', 'LinkedIn', 'Professional networks']
  },
  {
    id: 'cp_091',
    name: 'Javier Gonzalez',
    age: 41,
    gender: 'male',
    nationality: 'Argentine',
    ethnicity: 'Hispanic',
    location: 'Buenos Aires, Argentina',
    occupation: 'Cattle Rancher',
    industry: 'Agriculture',
    incomeLevel: 'high',
    educationLevel: 'bachelors',
    techComfort: 2,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'convenience',
    bio: 'Runs a large cattle ranch. Traditional approach but open to technology that improves efficiency.',
    painPoints: ['Market volatility', 'Climate', 'Export regulations'],
    goals: ['Quality beef', 'Sustainable ranching', 'Export growth'],
    preferredChannels: ['Agricultural associations', 'Trade shows', 'Personal networks']
  },
  {
    id: 'cp_092',
    name: 'Yuki Tanaka',
    age: 26,
    gender: 'female',
    nationality: 'Japanese',
    ethnicity: 'East Asian',
    location: 'Fukuoka, Japan',
    occupation: 'Content Creator',
    industry: 'Media',
    incomeLevel: 'medium',
    educationLevel: 'bachelors',
    techComfort: 5,
    decisionStyle: 'intuitive',
    riskTolerance: 'aggressive',
    buyingMotivation: 'innovation',
    bio: 'Full-time content creator with growing following. Values tools that enhance content production.',
    painPoints: ['Algorithm changes', 'Monetization', 'Content burnout'],
    goals: ['Audience growth', 'Brand partnerships', 'Creative freedom'],
    preferredChannels: ['YouTube', 'Instagram', 'TikTok']
  },
  {
    id: 'cp_093',
    name: 'Samuel Ochieng',
    age: 38,
    gender: 'male',
    nationality: 'Kenyan',
    ethnicity: 'East African',
    location: 'Kisumu, Kenya',
    occupation: 'Fish Farmer',
    industry: 'Agriculture',
    incomeLevel: 'medium',
    educationLevel: 'high_school',
    techComfort: 3,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'price',
    bio: 'Runs a fish farming operation. Focused on sustainable aquaculture. Values affordable, practical solutions.',
    painPoints: ['Feed costs', 'Market access', 'Technical knowledge'],
    goals: ['Production growth', 'Sustainable practices', 'Market expansion'],
    preferredChannels: ['Farmer groups', 'WhatsApp', 'Agricultural extension']
  },
  {
    id: 'cp_094',
    name: 'Anastasia Volkov',
    age: 29,
    gender: 'female',
    nationality: 'Ukrainian',
    ethnicity: 'Eastern European',
    location: 'Lviv, Ukraine',
    occupation: 'IT Recruiter',
    industry: 'Human Resources',
    incomeLevel: 'medium',
    educationLevel: 'bachelors',
    techComfort: 5,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'convenience',
    bio: 'Recruits IT talent for international companies. Values tools that help find and assess candidates.',
    painPoints: ['Talent competition', 'Remote hiring', 'Candidate assessment'],
    goals: ['Placement success', 'Agency growth', 'International clients'],
    preferredChannels: ['LinkedIn', 'IT communities', 'Professional networks']
  },
  {
    id: 'cp_095',
    name: 'Hassan El-Amin',
    age: 46,
    gender: 'male',
    nationality: 'Sudanese',
    ethnicity: 'North African',
    location: 'Khartoum, Sudan',
    occupation: 'Telecom Executive',
    industry: 'Telecommunications',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 4,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Executive at a telecom company. Focused on network expansion and digital services. Values reliable solutions.',
    painPoints: ['Infrastructure', 'Regulatory environment', 'Competition'],
    goals: ['Network coverage', 'Digital services', 'Market leadership'],
    preferredChannels: ['Telecom conferences', 'Industry associations', 'Vendor relationships']
  },
  {
    id: 'cp_096',
    name: 'Clara Hoffmann',
    age: 37,
    gender: 'female',
    nationality: 'Austrian',
    ethnicity: 'White European',
    location: 'Vienna, Austria',
    occupation: 'Classical Musician',
    industry: 'Arts',
    incomeLevel: 'medium',
    educationLevel: 'masters',
    techComfort: 2,
    decisionStyle: 'intuitive',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Professional violinist with an orchestra. Values quality and tradition. Open to tools that enhance performance.',
    painPoints: ['Career stability', 'Practice time', 'Performance opportunities'],
    goals: ['Artistic excellence', 'Solo opportunities', 'Teaching'],
    preferredChannels: ['Music networks', 'Concert venues', 'Personal contacts']
  },
  {
    id: 'cp_097',
    name: 'Budi Santoso',
    age: 43,
    gender: 'male',
    nationality: 'Indonesian',
    ethnicity: 'Southeast Asian',
    location: 'Jakarta, Indonesia',
    occupation: 'Palm Oil Producer',
    industry: 'Agriculture',
    incomeLevel: 'high',
    educationLevel: 'bachelors',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'moderate',
    buyingMotivation: 'quality',
    bio: 'Manages a palm oil plantation. Focused on sustainability certification. Values tools that support compliance.',
    painPoints: ['Sustainability pressure', 'Market access', 'Labor management'],
    goals: ['Sustainability certification', 'Premium markets', 'Operational efficiency'],
    preferredChannels: ['Industry associations', 'Certification bodies', 'Trade networks']
  },
  {
    id: 'cp_098',
    name: 'Nadia Petrova',
    age: 31,
    gender: 'female',
    nationality: 'Kazakh',
    ethnicity: 'Central Asian',
    location: 'Almaty, Kazakhstan',
    occupation: 'Fintech Founder',
    industry: 'Financial Services',
    incomeLevel: 'medium',
    educationLevel: 'masters',
    techComfort: 5,
    decisionStyle: 'intuitive',
    riskTolerance: 'aggressive',
    buyingMotivation: 'innovation',
    bio: 'Building a payments startup. Focused on financial inclusion. Values innovative, scalable solutions.',
    painPoints: ['Regulatory navigation', 'Funding', 'Market education'],
    goals: ['Product-market fit', 'Regional expansion', 'Financial inclusion impact'],
    preferredChannels: ['Startup events', 'LinkedIn', 'Fintech networks']
  },
  {
    id: 'cp_099',
    name: 'Emmanuel Nkosi',
    age: 50,
    gender: 'male',
    nationality: 'Zambian',
    ethnicity: 'Southern African',
    location: 'Lusaka, Zambia',
    occupation: 'Copper Mining Executive',
    industry: 'Mining',
    incomeLevel: 'very_high',
    educationLevel: 'masters',
    techComfort: 3,
    decisionStyle: 'analytical',
    riskTolerance: 'conservative',
    buyingMotivation: 'quality',
    bio: 'Executive at a copper mining company. Focused on operational excellence and community relations.',
    painPoints: ['Commodity prices', 'Environmental compliance', 'Community relations'],
    goals: ['Operational excellence', 'Sustainable mining', 'Community development'],
    preferredChannels: ['Mining conferences', 'Industry associations', 'Government relations']
  },
  {
    id: 'cp_100',
    name: 'Isabella Moretti',
    age: 34,
    gender: 'female',
    nationality: 'Italian',
    ethnicity: 'Mediterranean',
    location: 'Florence, Italy',
    occupation: 'Luxury Brand Manager',
    industry: 'Retail',
    incomeLevel: 'high',
    educationLevel: 'masters',
    techComfort: 4,
    decisionStyle: 'intuitive',
    riskTolerance: 'moderate',
    buyingMotivation: 'quality',
    bio: 'Manages a luxury fashion brand. Focused on brand heritage and digital transformation. Values quality and exclusivity.',
    painPoints: ['Digital vs physical balance', 'Counterfeiting', 'New consumer expectations'],
    goals: ['Brand growth', 'Digital excellence', 'Heritage preservation'],
    preferredChannels: ['Fashion events', 'Instagram', 'Luxury networks']
  }
];

// Helper functions
export const getPersonasByAgeRange = (minAge: number, maxAge: number): CustomerPersona[] => {
  return CUSTOMER_PERSONAS.filter(p => p.age >= minAge && p.age <= maxAge);
};

export const getPersonasByIndustry = (industry: string): CustomerPersona[] => {
  return CUSTOMER_PERSONAS.filter(p => p.industry.toLowerCase() === industry.toLowerCase());
};

export const getPersonasByNationality = (nationality: string): CustomerPersona[] => {
  return CUSTOMER_PERSONAS.filter(p => p.nationality.toLowerCase().includes(nationality.toLowerCase()));
};

export const getPersonasByTechComfort = (minLevel: number): CustomerPersona[] => {
  return CUSTOMER_PERSONAS.filter(p => p.techComfort >= minLevel);
};

export const getPersonasByIncomeLevel = (level: CustomerPersona['incomeLevel']): CustomerPersona[] => {
  return CUSTOMER_PERSONAS.filter(p => p.incomeLevel === level);
};

export const getRandomPersonas = (count: number): CustomerPersona[] => {
  const shuffled = [...CUSTOMER_PERSONAS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
};


export const getPersonasByRegion = (region: string): CustomerPersona[] => {
  // Map locations to regions
  const regionMap: Record<string, string[]> = {
    'Middle East': ['Dubai', 'Abu Dhabi', 'Riyadh', 'Jeddah', 'Doha', 'Kuwait', 'Muscat', 'Manama', 'Beirut', 'Amman', 'Tehran', 'Baghdad'],
    'North America': ['San Francisco', 'New York', 'Los Angeles', 'Chicago', 'Toronto', 'Vancouver', 'Miami', 'Seattle', 'Boston', 'Austin', 'Denver', 'Montreal'],
    'Europe': ['London', 'Paris', 'Berlin', 'Amsterdam', 'Madrid', 'Rome', 'Stockholm', 'Vienna', 'Zurich', 'Dublin', 'Barcelona', 'Munich', 'Copenhagen', 'Oslo', 'Helsinki', 'Prague', 'Warsaw', 'Florence'],
    'Asia Pacific': ['Singapore', 'Hong Kong', 'Tokyo', 'Sydney', 'Melbourne', 'Seoul', 'Shanghai', 'Beijing', 'Mumbai', 'Delhi', 'Bangalore', 'Jakarta', 'Manila', 'Bangkok', 'Kuala Lumpur', 'Ho Chi Minh', 'Auckland', 'Taipei'],
    'Africa': ['Lagos', 'Nairobi', 'Johannesburg', 'Cape Town', 'Cairo', 'Accra', 'Dar es Salaam', 'Addis Ababa', 'Kigali', 'Lusaka'],
    'Latin America': ['São Paulo', 'Mexico City', 'Buenos Aires', 'Bogotá', 'Lima', 'Santiago', 'Medellín', 'Rio de Janeiro']
  };
  
  const regionCities = regionMap[region] || [];
  return CUSTOMER_PERSONAS.filter(p => 
    regionCities.some(city => p.location.includes(city))
  );
};

export const getPersonaById = (id: string): CustomerPersona | undefined => {
  return CUSTOMER_PERSONAS.find(p => p.id === id);
};
