/**
 * Chief of Staff Quality Assurance Service
 * 
 * All documents generated by CEPHO.AI must pass through this QA layer
 * before delivery. The Chief of Staff reviews for brand compliance,
 * content quality, accuracy, and completeness.
 */

import { getDb } from "../db";
import { invokeLLM } from "../_core/llm";
import { 
  applyBrandFormatting, 
  validateBrandCompliance,
  runQAChecks,
  generateSignOffBlock,
  BRAND_GUIDELINES,
  type DocumentType,
  type ClassificationLevel,
  type DocumentStatus
} from "./documentTemplateService";

// QA Review status
export type QAStatus = "pending" | "approved" | "rejected" | "needs_revision";

// QA Review record
export interface QAReview {
  id: string;
  documentId: string;
  documentType: DocumentType;
  documentTitle: string;
  submittedAt: Date;
  reviewedAt?: Date;
  status: QAStatus;
  reviewerNotes: string;
  brandComplianceScore: number;
  contentQualityScore: number;
  overallScore: number;
  issues: string[];
  recommendations: string[];
  revisionHistory: {
    version: string;
    submittedAt: Date;
    status: QAStatus;
    notes: string;
  }[];
}

// QA Criteria weights
const QA_CRITERIA_WEIGHTS = {
  brandCompliance: 0.25,
  contentQuality: 0.25,
  accuracy: 0.20,
  completeness: 0.15,
  formatting: 0.10,
  classification: 0.05,
};

/**
 * Submit document for Chief of Staff QA review
 */
export async function submitForQAReview(
  documentId: string,
  documentType: DocumentType,
  documentTitle: string,
  content: string,
  classification: ClassificationLevel
): Promise<QAReview> {
  const reviewId = `QA-${Date.now().toString(36).toUpperCase()}`;
  
  // First, apply brand formatting to clean up content
  const formattedContent = applyBrandFormatting(content);
  
  // Validate brand compliance
  const brandValidation = validateBrandCompliance(formattedContent);
  
  // Run full QA checks
  const qaResult = await runQAChecks(formattedContent, {
    id: documentId,
    title: documentTitle,
    type: documentType,
    version: "1.0",
    createdAt: new Date(),
    updatedAt: new Date(),
    author: "CEPHO.AI",
    classification,
    status: "pending_review",
  });

  // Calculate scores
  const brandComplianceScore = qaResult.checks.brandCompliance ? 100 : 60;
  const contentQualityScore = qaResult.checks.contentQuality ? 100 : 70;
  const accuracyScore = qaResult.checks.accuracy ? 100 : 75;
  const completenessScore = qaResult.checks.completeness ? 100 : 65;
  const formattingScore = qaResult.checks.formatting ? 100 : 80;
  const classificationScore = qaResult.checks.classification ? 100 : 90;

  const overallScore = 
    brandComplianceScore * QA_CRITERIA_WEIGHTS.brandCompliance +
    contentQualityScore * QA_CRITERIA_WEIGHTS.contentQuality +
    accuracyScore * QA_CRITERIA_WEIGHTS.accuracy +
    completenessScore * QA_CRITERIA_WEIGHTS.completeness +
    formattingScore * QA_CRITERIA_WEIGHTS.formatting +
    classificationScore * QA_CRITERIA_WEIGHTS.classification;

  // Determine status based on score and issues
  let status: QAStatus = "pending";
  let reviewerNotes = "";

  if (overallScore >= 90 && qaResult.issues.length === 0) {
    status = "approved";
    reviewerNotes = "Document meets all CEPHO.AI quality standards. Approved for release.";
  } else if (overallScore >= 75 && qaResult.issues.length <= 2) {
    status = "approved";
    reviewerNotes = "Document approved with minor observations noted for future reference.";
  } else if (overallScore >= 60) {
    status = "needs_revision";
    reviewerNotes = "Document requires revisions before approval. See issues and recommendations.";
  } else {
    status = "rejected";
    reviewerNotes = "Document does not meet minimum quality standards. Significant revisions required.";
  }

  const review: QAReview = {
    id: reviewId,
    documentId,
    documentType,
    documentTitle,
    submittedAt: new Date(),
    reviewedAt: new Date(),
    status,
    reviewerNotes,
    brandComplianceScore,
    contentQualityScore,
    overallScore,
    issues: [...(brandValidation.issues || []), ...(qaResult.issues || [])],
    recommendations: qaResult.recommendations || [],
    revisionHistory: [{
      version: "1.0",
      submittedAt: new Date(),
      status,
      notes: reviewerNotes,
    }],
  };

  return review;
}

/**
 * Generate Chief of Staff review commentary
 */
export async function generateReviewCommentary(
  documentTitle: string,
  content: string,
  qaReview: QAReview
): Promise<string> {
  const response = await invokeLLM({
    messages: [
      {
        role: "system",
        content: `You are the CEPHO.AI Chief of Staff providing a quality assurance review.
        
Write a professional, constructive review commentary (2-3 paragraphs) that:
1. Summarizes the document's strengths
2. Identifies areas for improvement (if any)
3. Provides actionable recommendations
4. States the final decision (approved/needs revision/rejected)

Be direct, professional, and helpful. Avoid dramatic language.
Reference the CEPHO.AI brand guidelines where relevant.`
      },
      {
        role: "user",
        content: `Document: ${documentTitle}
        
QA Scores:
- Brand Compliance: ${qaReview.brandComplianceScore}/100
- Content Quality: ${qaReview.contentQualityScore}/100
- Overall: ${qaReview.overallScore.toFixed(0)}/100

Issues Found: ${qaReview.issues.length > 0 ? qaReview.issues.join("; ") : "None"}

Status: ${qaReview.status}

Document excerpt (first 2000 chars):
${content.substring(0, 2000)}`
      }
    ]
  });

  return typeof response.choices[0].message.content === 'string'
    ? response.choices[0].message.content
    : "Review commentary unavailable.";
}

/**
 * Apply automatic fixes for common issues
 */
export function applyAutomaticFixes(content: string): {
  fixedContent: string;
  fixesApplied: string[];
} {
  const fixesApplied: string[] = [];
  let fixedContent = content;

  // Fix 1: Apply brand formatting (removes hyphens, dramatic words)
  const beforeFormatting = fixedContent;
  fixedContent = applyBrandFormatting(fixedContent);
  if (fixedContent !== beforeFormatting) {
    fixesApplied.push("Applied brand formatting (removed hyphens and dramatic vocabulary)");
  }

  // Fix 2: Ensure proper section spacing
  fixedContent = fixedContent.replace(/\n{4,}/g, "\n\n\n");
  if (fixedContent !== content) {
    fixesApplied.push("Normalized section spacing");
  }

  // Fix 3: Ensure consistent heading format
  fixedContent = fixedContent.replace(/^(#+)\s*(\w)/gm, (match, hashes, firstChar) => {
    return `${hashes} ${firstChar.toUpperCase()}`;
  });

  // Fix 4: Remove trailing whitespace
  fixedContent = fixedContent.replace(/[ \t]+$/gm, "");

  // Fix 5: Ensure document ends with newline
  if (!fixedContent.endsWith("\n")) {
    fixedContent += "\n";
    fixesApplied.push("Added trailing newline");
  }

  return { fixedContent, fixesApplied };
}

/**
 * Generate QA sign-off stamp for approved documents
 */
export function generateQAStamp(qaReview: QAReview): string {
  if (qaReview.status !== "approved") {
    return "";
  }

  return `
---

## Chief of Staff Quality Assurance

| Criterion | Score | Status |
|-----------|-------|--------|
| Brand Compliance | ${qaReview.brandComplianceScore}/100 | ${qaReview.brandComplianceScore >= 80 ? "✓ Pass" : "⚠ Review"} |
| Content Quality | ${qaReview.contentQualityScore}/100 | ${qaReview.contentQualityScore >= 80 ? "✓ Pass" : "⚠ Review"} |
| **Overall** | **${qaReview.overallScore.toFixed(0)}/100** | **${qaReview.status === "approved" ? "✓ Approved" : "Pending"}** |

**Reviewed by:** Chief of Staff  
**Review Date:** ${qaReview.reviewedAt?.toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })}  
**Review ID:** ${qaReview.id}

*This document has been reviewed and approved in accordance with CEPHO.AI quality standards (CEPHO-BP-016).*

---
`;
}

/**
 * Process document through full QA pipeline
 */
export async function processDocumentQA(
  documentId: string,
  documentType: DocumentType,
  documentTitle: string,
  content: string,
  classification: ClassificationLevel = "internal"
): Promise<{
  finalContent: string;
  qaReview: QAReview;
  commentary: string;
  approved: boolean;
}> {
  // Step 1: Apply automatic fixes
  const { fixedContent, fixesApplied } = applyAutomaticFixes(content);
  
  // Step 2: Submit for QA review
  const qaReview = await submitForQAReview(
    documentId,
    documentType,
    documentTitle,
    fixedContent,
    classification
  );

  // Step 3: Generate review commentary
  const commentary = await generateReviewCommentary(documentTitle, fixedContent, qaReview);

  // Step 4: Add QA stamp if approved
  let finalContent = fixedContent;
  if (qaReview.status === "approved") {
    finalContent += generateQAStamp(qaReview);
  }

  return {
    finalContent,
    qaReview,
    commentary,
    approved: qaReview.status === "approved",
  };
}

/**
 * Get QA guidelines summary for document generation
 */
export function getQAGuidelines(): string {
  return `
## CEPHO.AI Document Quality Guidelines

### Brand Compliance
- Use CEPHO.AI logo in top left corner (40px height)
- Use approved colour palette (black, white, grey for documents)
- Use Inter font family for all text
- Maintain consistent typography hierarchy

### Content Quality
- Write in clear, professional language
- Avoid jargon, buzzwords, and dramatic vocabulary
- Use active voice and direct statements
- Provide actionable recommendations

### Formatting
- Include proper document ID and date
- Use appropriate classification marking
- Include Chief of Staff sign-off block
- Follow template structure for document type

### Prohibited
- Hyphens in compound words (except essential ones)
- Dramatic words: paradox, crisis, revolutionary, game-changing, synergy
- Vague or unsubstantiated claims
- Inconsistent formatting

Reference: CEPHO-BP-016 Brand Guidelines
`;
}
