import { BUSINESS_PLAN_SECTIONS, REVIEW_EXPERTS, BUSINESS_TEMPLATES } from './businessPlanReviewService';

export interface SectionReviewData {
  sectionId: string;
  sectionName: string;
  status: string;
  overallScore?: number;
  expertInsights: Array<{
    expertId: string;
    expertName: string;
    expertAvatar: string;
    insight: string;
    score: number;
    recommendations: string[];
    concerns: string[];
  }>;
  recommendations?: string[];
  concerns?: string[];
}

export interface PdfReportData {
  projectName: string;
  templateId?: string;
  reviewDate: Date;
  overallScore: number;
  sectionReviews: SectionReviewData[];
  expertTeam: string[];
  teamSelectionReasoning?: string;
}

// Generate markdown report content for PDF conversion
export function generateReportMarkdown(data: PdfReportData): string {
  const template = data.templateId 
    ? BUSINESS_TEMPLATES.find(t => t.id === data.templateId) 
    : null;
  
  const reviewDate = new Date(data.reviewDate).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  // Get unique experts involved
  const expertsInvolved = new Set<string>();
  data.sectionReviews.forEach(section => {
    section.expertInsights.forEach(insight => {
      expertsInvolved.add(insight.expertId);
    });
  });

  const expertProfiles = Array.from(expertsInvolved).map(id => 
    REVIEW_EXPERTS.find(e => e.id === id)
  ).filter(Boolean);

  // Calculate section scores
  const sectionScores = data.sectionReviews
    .filter(s => s.overallScore !== undefined)
    .map(s => ({
      name: s.sectionName,
      score: s.overallScore!,
      status: getScoreStatus(s.overallScore!)
    }));

  // Collect all recommendations and concerns
  const allRecommendations: string[] = [];
  const allConcerns: string[] = [];
  data.sectionReviews.forEach(section => {
    section.expertInsights.forEach(insight => {
      allRecommendations.push(...insight.recommendations);
      allConcerns.push(...insight.concerns);
    });
  });

  // Build markdown content
  let markdown = `# Business Plan Review Report

## ${data.projectName}

**Review Date:** ${reviewDate}

${template ? `**Business Type:** ${template.name}` : ''}

---

## Executive Summary

This comprehensive business plan review was conducted by a team of ${expertProfiles.length} SME experts, analyzing ${data.sectionReviews.length} key sections of the business plan.

**Overall Assessment Score: ${data.overallScore}/100**

${getOverallAssessment(data.overallScore)}

---

## Expert Team

${expertProfiles.map(expert => `- **${expert?.name}** - ${expert?.specialty}`).join('\n')}

${data.teamSelectionReasoning ? `\n**Team Selection Rationale:**\n${data.teamSelectionReasoning}\n` : ''}

---

## Section Analysis

`;

  // Add each section analysis
  data.sectionReviews.forEach(section => {
    const sectionDef = BUSINESS_PLAN_SECTIONS.find(s => s.id === section.sectionId);
    
    markdown += `### ${section.sectionName}

**Score: ${section.overallScore ?? 'N/A'}/100** ${getScoreEmoji(section.overallScore ?? 0)}

`;

    if (section.expertInsights.length > 0) {
      section.expertInsights.forEach(insight => {
        markdown += `#### ${insight.expertName}'s Analysis

${insight.insight}

**Recommendations:**
${insight.recommendations.map(r => `- ${r}`).join('\n')}

**Concerns:**
${insight.concerns.map(c => `- ${c}`).join('\n')}

`;
      });
    }

    markdown += `---

`;
  });

  // Key Recommendations Summary
  markdown += `## Key Recommendations

${getUniqueItems(allRecommendations).slice(0, 10).map((r, i) => `${i + 1}. ${r}`).join('\n')}

---

## Risk Areas and Concerns

${getUniqueItems(allConcerns).slice(0, 10).map((c, i) => `${i + 1}. ${c}`).join('\n')}

---

## Score Summary

| Section | Score | Status |
|---------|-------|--------|
${sectionScores.map(s => `| ${s.name} | ${s.score}/100 | ${s.status} |`).join('\n')}

---

${template ? `## ${template.name} Key Metrics to Track

${template.keyMetrics.map(m => `- ${m}`).join('\n')}

---

` : ''}

## Next Steps

Based on this review, we recommend focusing on the following areas:

1. Address the concerns raised in sections scoring below 70
2. Implement the key recommendations from each expert
3. Schedule follow-up reviews for sections requiring significant revision
4. Consider additional expert consultation for specialized areas

---

*This report was generated by CEPHO.Ai Business Plan Review System*
`;

  return markdown;
}

function getScoreStatus(score: number): string {
  if (score >= 80) return 'Strong';
  if (score >= 60) return 'Adequate';
  if (score >= 40) return 'Needs Work';
  return 'Critical';
}

function getScoreEmoji(score: number): string {
  if (score >= 80) return '✅';
  if (score >= 60) return '⚠️';
  return '❌';
}

function getOverallAssessment(score: number): string {
  if (score >= 80) {
    return 'The business plan demonstrates strong fundamentals across most areas. The expert team has identified several strengths and provided recommendations for further enhancement.';
  }
  if (score >= 60) {
    return 'The business plan shows promise but requires attention in several key areas. The expert team has provided specific recommendations to strengthen the overall proposition.';
  }
  if (score >= 40) {
    return 'The business plan requires significant revision in multiple sections. The expert team has identified critical areas that need immediate attention before proceeding.';
  }
  return 'The business plan needs substantial rework. The expert team recommends addressing the fundamental concerns before seeking investment or proceeding with execution.';
}

function getUniqueItems(items: string[]): string[] {
  const seen = new Set<string>();
  return items.filter(item => {
    const normalized = item.toLowerCase().trim();
    if (seen.has(normalized)) return false;
    seen.add(normalized);
    return true;
  });
}
