/**
 * Security Headers Middleware
 * Implements security best practices via HTTP headers using Helmet.js.
 *
 * CSP Strategy:
 *   - A per-request nonce is generated by `csp-nonce.ts` middleware and stored
 *     in `res.locals.cspNonce`.
 *   - Helmet reads that nonce via the callback form of `scriptSrc` / `styleSrc`,
 *     eliminating the need for `unsafe-inline` and `unsafe-eval`.
 *   - The nonce is injected into the HTML template by the Vite/static server layer.
 */

import helmet from "helmet";
import type { IncomingMessage, ServerResponse } from "node:http";
import type { Express, Request, Response, NextFunction } from "express";

/**
 * Apply security headers to all responses
 * Equivalent to helmet.js but lightweight and customized
 */
export function securityHeaders(
  req: Request,
  res: Response,
  next: NextFunction
) {
  // Prevent clickjacking attacks
  res.setHeader("X-Frame-Options", "DENY");

  // Prevent MIME type sniffing
  res.setHeader("X-Content-Type-Options", "nosniff");

  // Enable XSS protection (legacy browsers)
  res.setHeader("X-XSS-Protection", "1; mode=block");

  // Referrer policy - don't leak full URL
  res.setHeader("Referrer-Policy", "strict-origin-when-cross-origin");

  // Permissions policy - restrict browser features
  res.setHeader(
    "Permissions-Policy",
    ["camera=()", "microphone=()", "geolocation=()", "payment=()"].join(", ")
  );

  // Content Security Policy
  const cspDirectives = [
    "default-src 'self'",
    "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://accounts.google.com https://www.gstatic.com",
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
    "font-src 'self' https://fonts.gstatic.com data:",
    "img-src 'self' data: https: blob:",
    "connect-src 'self' https://accounts.google.com https://www.googleapis.com https://*.ingest.sentry.io https://sentry.io",
    "frame-src 'self' https://accounts.google.com",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "upgrade-insecure-requests",
  ];

  res.setHeader("Content-Security-Policy", cspDirectives.join("; "));

  // Strict Transport Security (HSTS) - only in production with HTTPS
  if (process.env.NODE_ENV === "production") {
    res.setHeader(
      "Strict-Transport-Security",
      "max-age=31536000; includeSubDomains; preload"
    );
  }

  next();
}

/**
 * CORS configuration for production
 */
export function corsHeaders(req: Request, res: Response, next: NextFunction) {
  const allowedOrigins = [
    "https://cepho.ai",
    "https://www.cepho.ai",
    "https://cepho-the-brain-complete.onrender.com",
  ];

  // In development, allow localhost
  if (process.env.NODE_ENV === "development") {
    allowedOrigins.push("http://localhost:5173", "http://localhost:3000");
  }

  const origin = req.headers.origin;

  if (origin && allowedOrigins.includes(origin)) {
    res.setHeader("Access-Control-Allow-Origin", origin);
    res.setHeader("Access-Control-Allow-Credentials", "true");
    res.setHeader(
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    );
    res.setHeader(
      "Access-Control-Allow-Headers",
      "Origin, X-Requested-With, Content-Type, Accept, Authorization, Cookie"
    );
    res.setHeader("Access-Control-Max-Age", "86400"); // 24 hours
  }

  // Handle preflight
  if (req.method === "OPTIONS") {
    return res.sendStatus(204);
  }

  next();
}

/**
 * Remove sensitive headers that leak server info
 */
export function removeServerHeaders(
  req: Request,
  res: Response,
  next: NextFunction
) {
  res.removeHeader("X-Powered-By");
  res.removeHeader("Server");
  next();
}

/**
 * Configure comprehensive security headers using Helmet.js.
 *
 * IMPORTANT: `cspNonceMiddleware` from `./csp-nonce.ts` MUST be applied before
 * this function so that `res.locals.cspNonce` is populated for every request.
 */
export function configureSecurityHeaders(app: Express) {
  app.use(
    helmet({
      contentSecurityPolicy: {
        directives: {
          defaultSrc: ["'self'"],
          // Nonce-based script allowlist — no unsafe-inline or unsafe-eval
          scriptSrc: [
            "'self'",
            // Helmet passes node:http IncomingMessage/ServerResponse; cast to access res.locals
            (_req: IncomingMessage, res: ServerResponse) =>
              `'nonce-${(res as unknown as Response).locals.cspNonce}'`,
            "https://cdn.jsdelivr.net",
            "https://accounts.google.com",
            "https://www.gstatic.com",
          ],
          // Style allowlist: nonce for injected styles + unsafe-inline for
          // component inline styles (e.g. recharts, framer-motion)
          styleSrc: [
            "'self'",
            "'unsafe-inline'",
            (_req: IncomingMessage, res: ServerResponse) =>
              `'nonce-${(res as unknown as Response).locals.cspNonce}'`,
            "https://fonts.googleapis.com",
          ],
          // Allow blob: workers for mermaid diagram rendering
          workerSrc: ["'self'", "blob:"],
          childSrc: ["'self'", "blob:"],
          scriptSrcAttr: ["'none'"],
          scriptSrcElem: [
            "'self'",
            (_req: IncomingMessage, res: ServerResponse) =>
              `'nonce-${(res as unknown as Response).locals.cspNonce}'`,
            "https://cdn.jsdelivr.net",
            "https://accounts.google.com",
            "https://www.gstatic.com",
          ],
          fontSrc: ["'self'", "https://fonts.gstatic.com", "data:"],
          imgSrc: ["'self'", "data:", "blob:", "https:"],
          connectSrc: [
            "'self'",
            "https://accounts.google.com",
            "https://www.googleapis.com",
            "https://oauth.manus.im",
            // Sentry error reporting — both US and EU ingest endpoints
            "https://*.ingest.sentry.io",
            "https://*.ingest.de.sentry.io",
            "https://sentry.io",
          ],
          frameSrc: ["'self'", "https://accounts.google.com"],
          objectSrc: ["'none'"],
          baseUri: ["'self'"],
          formAction: ["'self'"],
          upgradeInsecureRequests: [],
        },
      },
      hsts: {
        maxAge: 31536000,
        includeSubDomains: true,
        preload: true,
      },
      frameguard: { action: "deny" },
      noSniff: true,
      xssFilter: true,
      referrerPolicy: { policy: "strict-origin-when-cross-origin" },
      hidePoweredBy: true,
    })
  );
}

/**
 * Apply all security middleware
 * NOTE: securityHeaders (legacy function with unsafe-inline) is intentionally
 * NOT called here. configureSecurityHeaders uses Helmet with nonce-based CSP.
 */
export function applySecurityMiddleware(app: Express) {
  configureSecurityHeaders(app);
  app.use(removeServerHeaders);
  app.use(corsHeaders);
  // securityHeaders() is NOT applied — it contains unsafe-inline/unsafe-eval
  // and is superseded by the Helmet nonce-based CSP above.
}
